SIS.K12.Setup:
  description: "Setup (K12)"
  display_name: "Setup (K12)"
  type: form_group
  portal: sis
  sort: 4
  forms:
    School:
      description: "School"
      display_name: "School"
      sort: 4
      tabs:
        General:
          description: "General"
          display_name: "General"
          sort: 1
          route: sis_K12_school_schoolsetup_general
        Levels:
          description: "Levels"
          display_name: "Levels"
          sort: 2
          route: sis_K12_school_schoolsetup_levels
        GradeLevels:
          description: "Grade Levels"
          display_name: "Grade Levels"
          sort: 3
          route: sis_K12_school_schoolsetup_gradelevels



SIS.K12.Academic:
  description: "Academic"
  display_name: "Academic (K12)"
  portal: sis
  type: form_group
  sort: 3
  forms:
    Staff:
      description: "Staff"
      display_name: "Staff"
      sort: 3
      tabs: 
        Information:
          description: "Information"
          display_name: "Information"
          sort: 1
          route: sis_K12_school_staff
        OrganizationTerms:
          description: "Organization Terms"
          display_name: "Organization Terms"
          sort: 2
          route: sis_K12_school_staff_orgterms
      menu_actions:
        AddStaff:
          description: "Add Staff"
          display_name: "Add Staff"
          sort: 1
          route: sis_K12_school_staff_add
        DeleteStaff:
          description: "Delete Staff"
          display_name: "Delete Staff"
          sort: 2
          route: sis_K12_school_staff_delete
          divider_before: true
          record_loaded: true