Core.K12.Setup:
  description: "Setup"
  display_name: "Setup"
  type: dir
  parent: Core.K12
  forms:
    SchoolSetup:
      description: "School"
      display_name: "School"
      tabs:
        General:
          description: "General"
          display_name: "General"
          route: Core_K12_Setup_SchoolSetup_General
        Levels:
          description: "Levels"
          display_name: "Levels"
          route: Core_K12_Setup_SchoolSetup_Levels
        GradeLevels:
          description: "Grade Levels"
          display_name: "Grade Levels"
          route: Core_K12_Setup_SchoolSetup_GradeLevels

Core.K12.Staff:
  description: "Staff"
  display_name: "Staff"
  type: dir
  parent: Core.K12
  forms:
    Staff:
      description: "Staff"
      display_name: "Staff"
      tabs: 
        Information:
          description: "Information"
          display_name: "Information"
          route: Core_K12_Staff_Staff
        OrganizationTerms:
          description: "Organization Terms"
          display_name: "Organization Terms"
          route: Core_K12_Staff_Staff_OrgTerms
      button_add:
        route: Core_K12_Staff_Staff_Add
      button_delete:
        route: Core_K12_Staff_Staff_Delete
        record_loaded: true