Core.HEd.FinancialAid:
  parent: Core.HEd
  type: dir
  description: "Financial Aid"
  display_name: "Financial Aid"
  forms:
    FinancialAid:
      description: "Financial Aid"
      display_name: "Financial Aid"
      tabs:
        Pending:
          description: "Pending"
          display_name: "Pending"
          route: Core_HEd_FinancialAid_FinancialAid_Pending
        Posted:
          description: "Posted"
          display_name: "Posted"
          route: Core_HEd_FinancialAid_FinancialAid_Posted
        PowerFAIDS:
          description: "PowerFAIDS"
          display_name: "PowerFAIDS"
          route: Core_HEd_FinancialAid_FinancialAid_PowerFAIDS
    StudentFinancialAid:
      description: "Student Financial Aid"
      display_name: "Student Financial Aid"
      tabs:
        Package:
          description: "Package"
          display_name: "Package"
          route: Core_HEd_FinancialAid_StudentFinancialAid_Package
        Terms:
          description: "Terms"
          display_name: "Terms"
          route: Core_HEd_FinancialAid_StudentFinancialAid_Terms
        Awards:
          description: "Awards"
          display_name: "Awards"
          route: Core_HEd_FinancialAid_StudentFinancialAid_Awards
        AwardHistory:
          description: "Award History"
          display_name: "Award History"
          route: Core_HEd_FinancialAid_StudentFinancialAid_Awards_History
        Billing:
          description: "Billing"
          display_name: "Billing"
          route: Core_HEd_FinancialAid_StudentFinancialAid_Billing
        BillingHistory:
          description: "Billing History"
          display_name: "Billing History"
          route: Core_HEd_FinancialAid_StudentFinancialAid_Billing_History
    FinancialAidSetup:
      description: "Financial Aid Setup"
      display_name: "Financial Aid Setup"
      tabs:
        AwardCodes:
          description: "Award Codes"
          display_name: "Award Codes"
          route: Core_HEd_FinancialAid_FinancialAidSetup_AwardCodes
        PowerFAIDS:
          description: "PowerFAIDS"
          display_name: "PowerFAIDS"
          route: Core_HEd_FinancialAid_FinancialAidSetup_PowerFAIDS