Core_HEd_FinancialAid_StudentFinancialAid_Awards:
  path: /core/financial_aid/student/awards
  defaults: 
    _controller: KulaHEdFinancialAidBundle:CoreAwards:index
    _navigation: Core.HEd.FinancialAid.StudentFinancialAid.Awards

Core_HEd_FinancialAid_StudentFinancialAid_Awards_History:
  path: /core/financial_aid/student/award_history
  defaults: 
    _controller: KulaHEdFinancialAidBundle:CoreAwards:awards_history
    _navigation: Core.HEd.FinancialAid.StudentFinancialAid.AwardHistory

Core_HEd_FinancialAid_StudentFinancialAid_Billing:
  path: /core/financial_aid/student/billing
  defaults: 
    _controller: KulaHEdFinancialAidBundle:CoreAwards:billing
    _navigation: Core.HEd.FinancialAid.StudentFinancialAid.Billing
  methods: [GET]

Core_HEd_FinancialAid_StudentFinancialAid_Billing_History:
  path: /core/financial_aid/student/billing_history
  defaults: 
    _controller: KulaHEdFinancialAidBundle:CoreAwards:billing_history
    _navigation: Core.HEd.FinancialAid.StudentFinancialAid.BillingHistory

Core_HEd_FinancialAid_StudentFinancialAid_Package:
  path: /core/financial_aid/student/package
  defaults: 
    _controller: KulaHEdFinancialAidBundle:CorePackage:index
    _navigation: Core.HEd.FinancialAid.StudentFinancialAid.Package

Core_HEd_FinancialAid_StudentFinancialAid_Terms:
  path: /core/financial_aid/student/terms
  defaults: 
    _controller: KulaHEdFinancialAidBundle:CoreTerms:index
    _navigation: Core.HEd.FinancialAid.StudentFinancialAid.Terms

Core_HEd_Billing_FinancialAid_Pending:
  path: /core/billing/financial_aid/pending
  defaults: 
    _controller: KulaHEdFinancialAidBundle:CoreHomeFinancialAid:pending
    _navigation: Core.HEd.Billing.FinancialAid.Pending

Core_HEd_Billing_FinancialAid_Posted:
  path: /core/billing/financial_aid/posted
  defaults: 
    _controller: KulaHEdFinancialAidBundle:CoreHomeFinancialAid:posted
    _navigation: Core.HEd.Billing.FinancialAid.Posted

Core_HEd_FinancialAid_FinancialAidSetup_AwardCodes:
  path: /core/financial_aid/setup/award_codes
  defaults: 
    _controller: KulaHEdFinancialAidBundle:CoreCodes:award_codes
    _navigation: Core.HEd.FinancialAid.FinancialAidSetup.AwardCodes
  
Core_HEd_FinancialAid_PowerFAIDS:
  path: /core/financial_aid/powerfaids
  defaults: 
    _controller: KulaHEdFinancialAidBundle:CorePFAIDS:admin
    _navigation: Core.HEd.FinancialAid.PowerFAIDS
  
Core_HEd_FinancialAid_FinancialAidSetup_PowerFAIDS:
  path: /core/financial_aid/setup/powerfaids
  defaults: 
    _controller: KulaHEdFinancialAidBundle:CorePFAIDS:config
    _navigation: Core.HEd.FinancialAid.FinancialAidSetup.PowerFAIDS

Core_HEd_FinancialAid_StudentFinancialAid_SyncFAPFAIDS:
  path: /core/financial_aid/sync/powerfaids
  defaults: 
    _controller: KulaHEdFinancialAidBundle:CorePFAIDS:syncFA
    _navigation: Core.HEd.FinancialAid.StudentFinancialAid.SyncFAPFAIDS
  methods: [GET]
  
Core_HEd_FinancialAid_StudentFinancialAid_SyncFAPFAIDS_calculate:
  path: /core/financial_aid/sync/powerfaids
  defaults: 
    _controller: KulaHEdFinancialAidBundle:CorePFAIDS:performSyncFA
  methods: [POST]