imports:
    - { resource: schema/code.yml }
    - { resource: schema/award.yml }

Core.Lookup.Value:
  fields:
    PFCode:
      description: "PowerFAIDS Code"
      db_column_name: PF_CODE
      db_column_type: varchar
      db_column_length: 255
      db_column_null: true
      field_type: text
      field_size: 10
      column_name: "PF Code"
      label_name: "PF Code"

HEd.Degree:
  fields:
    PFCode:
      description: "PowerFAIDS Code"
      db_column_name: PF_CODE
      db_column_type: varchar
      db_column_length: 255
      db_column_null: true
      field_type: text
      field_size: 10
      column_name: "PF Code"
      label_name: "PF Code"

HEd.Degree.Area:
  fields:
    PFCode:
      description: "PowerFAIDS Code"
      db_column_name: PF_CODE
      db_column_type: varchar
      db_column_length: 255
      db_column_null: true
      field_type: text
      field_size: 10
      column_name: "PF Code"
      label_name: "PF Code"

HEd.Student.Status:
  fields:
    PFaidsExempt:
      description: "PowerFAIDS Exempt"
      db_column_name: PFAIDS_EXEMPT
      db_column_type: bool
      db_column_default: 0
      db_column_null: false
      field_type: checkbox
      column_name: "PowerFAIDS Exempt"
      label_name: "PowerFAIDS Exempt"