Core.HEd.Setup:
  description: "Setup"
  display_name: "Setup"
  type: dir
  parent: Core.HEd
  forms:
    School:
      description: "School"
      display_name: "School"
      tabs:
        General:
          description: "General"
          display_name: "General"
          route: core_HEd_school_schoolsetup_general
        Levels:
          description: "Levels"
          display_name: "Levels"
          route: core_HEd_school_schoolsetup_levels
        GradeLevels:
          description: "Grade Levels"
          display_name: "Grade Levels"
          route: core_HEd_school_schoolsetup_gradelevels

Core.HEd.Staff:
  description: "Staff"
  display_name: "Staff"
  type: dir
  parent: Core.HEd
  forms:
    Staff:
      description: "Staff"
      display_name: "Staff"
      tabs: 
        Information:
          description: "Information"
          display_name: "Information"
          route: core_HEd_school_staff
        OrganizationTerms:
          description: "Organization Terms"
          display_name: "Organization Terms"
          route: core_HEd_school_staff_orgterms
        Addresses:
          description: "Addresses"
          display_name: "Addresses"
          route: core_HEd_school_staff_addresses
        Phones:
          description: "Phones"
          display_name: "Phones"
          route: core_HEd_school_staff_phones
        EmailAddresses:
          description: "Email Addresses"
          display_name: "Email Addresses"
          route: core_HEd_school_staff_emailaddress
        EmergencyContacts:
          description: "Emergency Contacts"
          display_name: "Emergency Contacts"
          route: core_HEd_school_staff_emergencycontacts
      menu_actions:
        NewAddress:
          description: "New Address"
          display_name: "New Address"
          record_loaded: true
          route: core_HEd_school_staff_addresses_add
      button_add:
        route: core_HEd_school_staff_add
      button_delete:
        route: core_HEd_school_staff_delete