core_HEd_student_information_add:
  path: /student/information/add
  defaults: 
    _controller: KulaHEdStudentBundle:CoreInformation:add
    _navigation: Core.HEd.Student.Information

core_HEd_student_information_add_constituent:
  path: /student/information/add/constituent
  defaults: 
    _controller: KulaHEdStudentBundle:CoreInformation:add_constituent
    _navigation: Core.HEd.Student.Information
  methods: [GET]

core_HEd_student_information_addresses:
  path: /student/information/addresses
  defaults: 
    _controller: KulaHEdStudentBundle:CoreContactInfo:addresses
    _navigation: Core.HEd.Student.Information.Addresses

core_HEd_student_information_addresses_detail:
  path: /student/{id}/information/addresses/detail/{sub_id}
  defaults: 
    _controller: KulaHEdStudentBundle:CoreContactInfo:detail
    _navigation: Core.HEd.Student.Information.Addresses

core_HEd_student_information_basic:
  path: /student/information/basic
  defaults: 
    _controller: KulaHEdStudentBundle:CoreInformation:basic
    _navigation: Core.HEd.Student.Information.Basic

core_HEd_student_information_create_constituent:
  path: /student/information/add/constituent
  defaults: 
    _controller: KulaHEdStudentBundle:CoreInformation:create_constituent
    _navigation: Core.HEd.Student.Information
  methods: [POST]

core_HEd_student_information_demographic:
  path: /student/information/demographic
  defaults: 
    _controller: KulaHEdStudentBundle:CoreInformation:demographic
    _navigation: Core.HEd.Student.Information.Demographic

core_HEd_student_information_emailaddres:
  path: /student/information/emailaddresses
  defaults: 
    _controller: KulaHEdStudentBundle:CoreContactInfo:emailAddresses
    _navigation: Core.HEd.Student.Information.EmailAddresses

core_HEd_student_information_emergencycontacts:
  path: /student/information/emergencycontacts
  defaults: 
    _controller: KulaHEdStudentBundle:CoreContactInfo:emergencyContacts
    _navigation: Core.HEd.Student.Information.EmergencyContacts

core_HEd_student_enrollment_edit:
  path: /student/enrollment/edit
  defaults: 
    _controller: KulaHEdStudentBundle:CoreEnrollment:edit
    _navigation: Core.HEd.Student.Enrollment

core_HEd_student_information_otherinfo:
  path: /student/information/otherinfo
  defaults: 
    _controller: KulaHEdStudentBundle:CoreInformation:other_info
    _navigation: Core.HEd.Student.Information.Other

core_HEd_student_information_userinfo:
  path: /student/information/userinfo
  defaults: 
    _controller: KulaHEdStudentBundle:CoreInformation:user_info
    _navigation: Core.HEd.Student.Information.User

core_HEd_student_information_phones:
  path: /student/information/phones
  defaults: 
    _controller: KulaHEdStudentBundle:CoreContactInfo:phones
    _navigation: Core.HEd.Student.Information.Phones

core_HEd_student_information_addresses_add:
  path: /student/information/addresses/add
  defaults: 
    _controller: KulaHEdStudentBundle:CoreContactInfo:add_address
    _navigation: Core.HEd.Student.Information.Addresses

core_HEd_student_holds:
  path: /student/holds
  defaults: 
    _controller: KulaHEdStudentBundle:CoreHolds:index
    _navigation: Core.HEd.Holds.StudentHolds

core_HEd_student_forms:
  path: /student/forms
  defaults: 
    _controller: KulaHEdStudentBundle:CoreForms:studentForms
    _navigation: Core.HEd.Forms.StudentForms

core_HEd_student_documents:
  path: /student/documents
  defaults: 
    _controller: KulaHEdStudentBundle:CoreDocuments:index
    _navigation: Core.HEd.Student.Documents

core_HEd_student_enrollment_activateinactivate:
  path: /student/enrollment/activateinactivate
  defaults: 
    _controller: KulaHEdStudentBundle:CoreEnrollment:activateinactivate
    _navigation: Core.HEd.Student.Enrollment.ActivateInactivate

core_HEd_student_enrollment_activitydetail:
  path: /student/enrollment/activity/{student_enrollment_id}
  defaults: 
    _controller: KulaHEdStudentBundle:CoreEnrollment:activity
    _navigation: Core.HEd.Student.Enrollment.Statuses

core_HEd_student_enrollment_enrollmentdetail:
  path: /student/enrollment/enrollments/{student_status_id}
  defaults: 
    _controller: KulaHEdStudentBundle:CoreEnrollment:enrollments
    _navigation: Core.HEd.Student.Enrollment.Statuses

core_HEd_student_enrollment_reports_enrollmentverification:
  path: /student/enrollment/reports/enrollmentverification
  defaults: 
    _controller: KulaHEdStudentBundle:CoreEnrollmentVerificationReport:index
    _navigation: Core.HEd.Student.Reports.EnrollmentVerification
  methods: [GET]

core_HEd_student_enrollment_reports_enrollmentverification_generate:
  path: /student/enrollment/reports/enrollmentverification
  defaults: 
    _controller: KulaHEdStudentBundle:CoreEnrollmentVerificationReport:generate
    _navigation: Core.HEd.Student.Reports.EnrollmentVerification
  methods: [POST]

core_HEd_student_enrollment_statuses:
  path: /student/enrollment
  defaults: 
    _controller: KulaHEdStudentBundle:CoreEnrollment:index
    _navigation: Core.HEd.Student.Enrollment.Statuses

core_HEd_setup_student_documents:
  path: /setup/student/documents
  defaults: 
    _controller: KulaHEdStudentBundle:CoreDocumentsSetup:document_codes
    _navigation: Core.HEd.Student.Setup.Documents

core_HEd_setup_student_holds:
  path: /setup/student/holds
  defaults: 
    _controller: KulaHEdStudentBundle:CoreHoldsSetup:hold_codes
    _navigation: Core.HEd.Holds.SetupHolds

core_HEd_setup_student_forms:
  path: /setup/student/forms
  defaults: 
    _controller: KulaHEdStudentBundle:CoreForms:setup
    _navigation: Core.HEd.Forms.FormsSetup

core_HEd_home_holds:
  path: /home/holds
  defaults: 
    _controller: KulaHEdStudentBundle:CoreHomeHolds:index
    _navigation: Core.HEd.Holds.Holds

core_HEd_student_chooser:
  path: /student/chooser
  defaults: { _controller: KulaHEdStudentBundle:CoreInformation:chooser }

core_HEd_student_information_parents:
  path: /student/information/parents
  defaults: 
    _controller: KulaHEdStudentBundle:CoreParents:studentParents
    _navigation: Core.HEd.Student.Information.Parents

core_HEd_student_information_parents_add:
  path: /student/information/parents/add
  defaults: 
    _controller: KulaHEdStudentBundle:CoreParents:add
    _navigation: Core.HEd.Student.Information.Parents
  
Core_HEd_Student_Parents_Add_Constituent:
  path: /student/information/parents/add/constituent
  defaults: { _controller: KulaHEdStudentBundle:CoreParents:add_constituent }
  methods: [GET]

Core_HEd_Student_Parents_Create_Constituent:
  path: /student/information/parents/add/constituent
  defaults: { _controller: KulaHEdStudentBundle:CoreParents:create_constituent }
  methods: [POST]


core_HEd_student_parent_basic:
  path: /student/parents
  defaults:
    _controller: KulaHEdStudentBundle:CoreParent:index
    _navigation: 

core_HEd_student_parent_children:
  path: /student/parents/children
  defaults: 
    _controller: KulaHEdStudentBundle:CoreParent:children
    _navigation: 

core_HEd_student_parent_delete:
  path: /student/parent/delete
  defaults: { _controller: KulaHEdStudentBundle:CoreParent:delete }
  methods: [POST]

core_HEd_student_parent_addresses:
  path: /student/parent/addresses
  defaults: 
    _controller: KulaHEdStudentBundle:CoreParentsContactInfo:addresses
    _navigation: 

core_HEd_student_parent_addresses_detail:
  path: /student/parent/{id}/addresses/detail/{sub_id}
  defaults: 
    _controller: KulaHEdStudentBundle:CoreParentsContactInfo:detail
    _navigation: 

core_HEd_student_parent_addresses_add:
  path: /student/parent/addresses/add
  defaults: 
    _controller: KulaHEdStudentBundle:CoreParentsContactInfo:add_address
    _navigation: 

core_HEd_student_parent_phones:
  path: /student/parent/phones
  defaults: 
    _controller: KulaHEdStudentBundle:CoreParentsContactInfo:phones
    _navigation: Core.HEd.Student.Parent.Phone
  
core_HEd_student_parent_EmailAddresses:
  path: /student/parent/email_addresses
  defaults: 
    _controller: KulaHEdStudentBundle:CoreParentsContactInfo:emailAddresses
    _navigation: Core.HEd.Student.Parent.EmailAddresses