sis_HEd_student_information_add:
  path: /student/information/add
  defaults: { _controller: KulaHEdStudentBundle:SISInformation:add }

sis_HEd_student_information_add_constituent:
  path: /student/information/add/constituent
  defaults: { _controller: KulaHEdStudentBundle:SISInformation:add_constituent }
  methods: [GET]

sis_HEd_student_information_addresses:
  path: /student/information/addresses
  defaults: { _controller: KulaHEdStudentBundle:SISContactInfo:addresses }

sis_HEd_student_information_addresses_detail:
  path: /student/{id}/information/addresses/detail/{sub_id}
  defaults: { _controller: KulaHEdStudentBundle:SISContactInfo:detail }

sis_HEd_student_information_basic:
  path: /student/information/basic
  defaults: { _controller: KulaHEdStudentBundle:SISInformation:basic }

sis_HEd_student_information_create_constituent:
  path: /student/information/add/constituent
  defaults: { _controller: KulaHEdStudentBundle:SISInformation:create_constituent }
  methods: [POST]

sis_HEd_student_information_demographic:
  path: /student/information/demographic
  defaults: { _controller: KulaHEdStudentBundle:SISInformation:demographic }

sis_HEd_student_information_emailaddres:
  path: /student/information/emailaddresses
  defaults: { _controller: KulaHEdStudentBundle:SISContactInfo:emailAddresses }

sis_HEd_student_information_emergencycontacts:
  path: /student/information/emergencycontacts
  defaults: { _controller: KulaHEdStudentBundle:SISContactInfo:emergencyContacts }

sis_HEd_student_information_enrollment:
  path: /student/information/enrollment
  defaults: { _controller: KulaHEdStudentBundle:SISInformation:enrollment }

sis_HEd_student_information_otherinfo:
  path: /student/information/otherinfo
  defaults: { _controller: KulaHEdStudentBundle:SISInformation:other_info }

sis_HEd_student_information_phones:
  path: /student/information/phones
  defaults: { _controller: KulaHEdStudentBundle:SISContactInfo:phones }

sis_HEd_student_information_addresses_add:
  path: /student/information/addresses/add
  defaults: { _controller: KulaHEdStudentBundle:SISContactInfo:add_address }

sis_HEd_student_holds:
  path: /student/holds
  defaults: { _controller: KulaHEdStudentBundle:SISHolds:index }

sis_HEd_student_documents:
  path: /student/documents
  defaults: { _controller: KulaHEdStudentBundle:SISDocuments:index }

sis_HEd_student_enrollment_activateinactivate:
  path: /student/enrollment/activateinactivate
  defaults: { _controller: KulaHEdStudentBundle:SISEnrollment:activateinactivate }

sis_HEd_student_enrollment_activitydetail:
  path: /student/enrollment/activity/{student_enrollment_id}
  defaults: { _controller: KulaHEdStudentBundle:SISEnrollment:activity }

sis_HEd_student_enrollment_enrollmentdetail:
  path: /student/enrollment/enrollments/{student_status_id}
  defaults: { _controller: KulaHEdStudentBundle:SISEnrollment:enrollments }

sis_HEd_student_enrollment_reports_enrollmentverification:
  path: /student/enrollment/reports/enrollmentverification
  defaults: { _controller: KulaHEdStudentBundle:SISEnrollmentVerificationReport:index }
  methods: [GET]

sis_HEd_student_enrollment_reports_enrollmentverification_generate:
  path: /student/enrollment/reports/enrollmentverification
  defaults: { _controller: KulaHEdStudentBundle:SISEnrollmentVerificationReport:generate }
  methods: [POST]

sis_HEd_student_enrollment_statuses:
  path: /student/enrollment
  defaults: { _controller: KulaHEdStudentBundle:SISEnrollment:index }

sis_HEd_setup_student_documents:
  path: /setup/student/documents
  defaults: { _controller: KulaHEdStudentBundle:SISDocumentsSetup:document_codes }

sis_HEd_setup_student_holds:
  path: /setup/student/holds
  defaults: { _controller: KulaHEdStudentBundle:SISHoldsSetup:hold_codes }

sis_HEd_home_holds:
  path: /home/holds
  defaults: { _controller: KulaHEdStudentBundle:SISHomeHolds:index }
