K12.Section:
  fields:
    AllowRegistration:
      description: "Allow Registration"
      db_column_name: ALLOW_REGISTRATION
      db_column_type: bool
      db_column_default: 1
      db_column_null: false
      field_type: checkbox
      columnn_name: "Allow Registration"
      label_name: "Allow Registration"
    OpenRegistration:
      description: "Open Registration"
      db_column_name: OPEN_REGISTRATION
      db_column_type: datetime
      db_column_null: true
      field_type: datetime
      columnn_name: "Open Registration"
      label_name: "Open Registration"
    CloseRegistration:
      description: "Close Registration"
      db_column_name: CLOSE_REGISTRATION
      db_column_type: datetime
      db_column_null: true
      field_type: datetime
      column_name: "Close Registration"
      label_name: "Close Registration"
    ParentEnroll:
      description: "Parent Must Enroll"
      db_column_name: PARENT_ENROLL
      db_column_type: bool
      db_column_default: 0
      field_type: checkbox
      column_name: "Parent Must Enroll"
      label_name: "Parent Must Enroll"