Core.K12.Student:
  type: dir
  parent: Core.K12
  description: "Student"
  display_name: "Student"
  forms: 
    Student:
      description: "Student"
      display_name: "Student"
      tabs:
        Basic:
          description: "Basic"
          display_name: "Basic"
          route: Core_K12_Student_Student_Basic
        Demographic:
          description: "Demographic"
          display_name: "Demographic"
          route: Core_K12_Student_Student_Demographic
        Parents:
          description: "Parents"
          display_name: "Parents"
          route: Core_K12_Student_Student_Parents
        Addresses:
          description: "Addresses"
          display_name: "Addresses"
          route: Core_K12_Student_Student_Addresses
        Phones:
          description: "Phones"
          display_name: "Phones"
          route: Core_K12_Student_Student_Phones
        EmailAddresses:
          description: "Email Addresses"
          display_name: "Email Addresses"
          route: Core_K12_Student_Student_EmailAddresses
        EmergencyContacts:
          description: "Emergency Contacts"
          display_name: "Emergency Contacts"
          route: Core_K12_Student_Student_EmergencyContacts
        Other:
          description: "Other Information"
          display_name: "Other Info"
          route: Core_K12_Student_Student_OtherInfo
      button_add:
        route: Core_K12_Student_Student_Add
      menu_actions:
        NewAddress:
          description: "New Address"
          display_name: "New Address"
          record_loaded: true
          route: Core_K12_Student_Student_Addresses_Add
        NewParent:
          description: "New Parent"
          display_name: "New Parent"
          divider_before: true
          record_loaded: true
          route: Core_K12_Student_Student_Parents_Add
    Enrollment:
      description: "Enrollment"
      display_name: "Enrollment"
      route: Core_K12_Student_Enrollment_Statuses
      menu_actions:
        ActivateInactivate:
          description: "Activate/Inactivate"
          display_name: "Activate/Inactivate"
          record_loaded: true
          route: Core_K12_Student_Enrollment_ActivateInactivate
        Edit:
          description: "Edit Enrollment"
          display_name: "Edit Enrollment"
          record_loaded: true
          route: Core_K12_Student_Enrollment_Edit
    Parent:
      description: "Parent"
      display_name: "Parent"
      tabs:
        Basic:
          description: "Basic"
          display_name: "Basic"
          route: Core_K12_Student_Parent_Basic
        Children:
          description: "Children"
          display_name: "Children"
          route: Core_K12_Student_Parent_Children
        Addresses:
          description: "Addresses"
          display_name: "Addresses"
          route: Core_K12_Student_Parent_Addresses
        Phones:
          description: "Phones"
          display_name: "Phones"
          route: Core_K12_Student_Parent_Phones
        EmailAddresses:
          description: "Email Addresses"
          display_name: "Email Addresses"
          route: Core_K12_Parent_EmailAddresses
      menu_actions:
        NewAddress:
          description: "New Address"
          display_name: "New Address"
          record_loaded: true
          route: Core_K12_Student_Parent_Addresses_Add
      button_delete:
        route: Core_K12_Student_Parent_Delete
