SIS.K12.Student:
  description: "Student K12"
  display_name: "Student (K12)"
  type: form_group
  portal: sis
  sort: 1
  forms: 
    Information:
      description: "Information"
      display_name: "Information"
      sort: 1
      tabs:
        Basic:
          description: "Basic"
          display_name: "Basic"
          sort: 1
          route: sis_K12_student_information_basic
        Demographic:
          description: "Demographic"
          display_name: "Demographic"
          sort: 2
          route: sis_K12_student_information_demographic
        Parents:
          description: "Parents"
          display_name: "Parents"
          sort: 3
          route: sis_K12_student_information_parents
        Addresses:
          description: "Addresses"
          display_name: "Addresses"
          sort: 4
          route: sis_K12_student_information_addresses
        Phones:
          description: "Phones"
          display_name: "Phones"
          sort: 5
          route: sis_K12_student_information_phones
        EmailAddresses:
          description: "Email Addresses"
          display_name: "Email Addresses"
          sort: 6
          route: sis_K12_student_information_emailaddres
        EmergencyContacts:
          description: "Emergency Contacts"
          display_name: "Emergency Contacts"
          sort: 7
          route: sis_K12_student_information_emergencycontacts
        Other:
          description: "Other Information"
          display_name: "Other Info"
          sort: 8
          route: sis_K12_student_information_otherinfo
      menu_actions:
        NewStudent:
          description: "New Student"
          display_name: "New Student"
          route: sis_K12_student_information_add
          sort: 1
        NewAddress:
          description: "New Address"
          display_name: "New Address"
          divider_before: true
          record_loaded: true
          route: sis_K12_student_information_addresses_add
          sort: 2
        NewParent:
          description: "New Parent"
          display_name: "New Parent"
          divider_before: true
          record_loaded: true
          route: sis_K12_student_information_parents_add
          sort: 3
    Enrollment:
      description: "Enrollment"
      display_name: "Enrollment"
      route: sis_K12_student_enrollment_statuses
      sort: 2
      menu_actions:
        ActivateInactivate:
          description: "Activate/Inactivate"
          display_name: "Activate/Inactivate"
          record_loaded: true
          route: sis_K12_student_enrollment_activateinactivate
          sort: 1
        Edit:
          description: "Edit Enrollment"
          display_name: "Edit Enrollment"
          record_loaded: true
          sort: 2
          route: sis_K12_student_enrollment_edit
    Parents:
      description: "Parents"
      display_name: "Parents"
      sort: 3
      tabs:
        Basic:
          description: "Basic"
          display_name: "Basic"
          sort: 1
          route: sis_K12_parent_basic
        Children:
          description: "Children"
          display_name: "Children"
          sort: 2
          route: sis_K12_parent_children
        Addresses:
          description: "Addresses"
          display_name: "Addresses"
          sort: 4
          route: sis_K12_parent_addresses
        Phones:
          description: "Phones"
          display_name: "Phones"
          sort: 5
          route: sis_K12_parent_phones
        EmailAddresses:
          description: "Email Addresses"
          display_name: "Email Addresses"
          sort: 6
          route: sis_K12_parent_emailaddress
      menu_actions:
        NewAddress:
          description: "New Address"
          display_name: "New Address"
          record_loaded: true
          route: sis_K12_parent_addresses_add
          sort: 1
        Delete:
          description: "Delete Parent"
          display_name: "Delete Parent"
          record_loaded: true
          divider_before: true
          route: sis_K12_parent_delete
          sort: 2

SIS.K12.Reports.Student:
  description: "Student (K12)"
  display_name: "Student (K12)"
  type: report_group
  portal: sis
  sort: 1
  reports:
    EnrollmentVerification:
      description: "Enrollment Verification"
      display_name: "Enrollment Verification"
      route: sis_K12_student_enrollment_reports_enrollmentverification
      sort: 1