imports:
    - { resource: schema/student.yml }
    - { resource: schema/enrollment.yml }
    - { resource: schema/emergency.yml }
    - { resource: schema/parent.yml }
    - { resource: schema/school.yml }