api_v1_courses:
    path:     /{org}/{term}/course
    defaults: { _controller: KulaHEdSchedulingBundle:APIv1Course:courses }
    methods: [GET]

api_v1_course:
    path:     /{org}/{term}/course/{section_id}
    defaults: { _controller: KulaHEdSchedulingBundle:APIv1Course:course }
    methods: [GET]

api_v1_add_class:
    path:     /student/{student_id}/classes/add/{section_id}
    defaults: { _controller: KulaHEdSchedulingBundle:APIv1Schedule:addClass }
    methods: [POST]

api_v1_delete_class:
    path:     /student/{student_id}/classes/{class_id}
    defaults: { _controller: KulaHEdSchedulingBundle:APIv1Schedule:removeClass }
    methods: [DELETE]

api_v1_classes:
    path:     /student/{student_id}/classes
    defaults: { _controller: KulaHEdSchedulingBundle:APIv1Schedule:getClasses }
    methods: [GET]

api_v1_classes_org_term:
    path:     /student/{student_id}/classes/{org}/{term}
    defaults: { _controller: KulaHEdSchedulingBundle:APIv1Schedule:getClasses }
    methods: [GET]

api_v1_classes_pending:
    path:    /student/current/classes/pending
    defaults: { _controller: KulaHEdSchedulingBundle:APIv1Schedule:getPendingClasses }