api_v1_courses:
    path:     /{org}/{term}/course
    defaults: { _controller: KulaHEdSchedulingBundle:APIv1Course:courses }
    methods: [GET]

api_v1_course:
    path:     /{org}/{term}/course/{section_id}
    defaults: { _controller: KulaHEdSchedulingBundle:APIv1Course:course }
    methods: [GET]

api_v1_add_class:
    path:     /student/{student_id}/classes/add/{section_id}
    defaults: { _controller: KulaHEdSchedulingBundle:APIv1Schedule:addClass }
    methods: [POST]