sis_HEd_offering_staff_schedule:
  path: /offering/staff/schedule
  defaults: { _controller: KulaHEdSchedulingBundle:Staff:staff_schedule }

sis_HEd_student_schedule:
  path: /student/schedule
  defaults: { _controller: KulaHEdSchedulingBundle:Schedule:index }

sis_HEd_student_schedule_add:
  path: /student/schedule/add
  defaults: { _controller: KulaHEdSchedulingBundle:Schedule:add }

sis_HEd_student_schedule_calculateTotals:
  path: /student/schedule/calculateTotals
  defaults: { _controller: KulaHEdSchedulingBundle:Schedule:calculateTotals }

sis_HEd_student_schedule_detail_edit:
  path: /student/{id}/schedule/detail/{sub_id}
  defaults: { _controller: KulaHEdSchedulingBundle:Schedule:detail }

sis_HEd_student_schedule_grades:
  path: /student/schedule/grades
  defaults: { _controller: KulaHEdSchedulingBundle:Schedule:grades }

sis_HEd_student_schedule_history:
  path: /student/schedule/history
  defaults: { _controller: KulaHEdSchedulingBundle:Schedule:history }

sis_HEd_student_schedule_reports_studentschedule:
  path: /student/schedule/reports/studentschedule
  defaults: { _controller: KulaHEdSchedulingBundle:StudentScheduleReport:index }
  methods: [GET]

sis_HEd_student_schedule_reports_studentschedule_generate:
  path: /student/schedule/reports/studentschedule
  defaults: { _controller: KulaHEdSchedulingBundle:StudentScheduleReport:generate }
  methods: [POST]

sis_HEd_student_schedule_reports_ss_studentschedule:
  path: /student/schedule/reports/ss/studentschedule
  defaults: { _controller: KulaHEdSchedulingBundle:SSStudentScheduleReport:index }
  methods: [GET]
  
sis_HEd_student_schedule_reports_ss_studentschedule_generate:
  path: /student/schedule/reports/ss/studentschedule
  defaults: { _controller: KulaHEdSchedulingBundle:SSStudentScheduleReport:generate }
  methods: [POST]

sis_HEd_student_schedule_waitlist:
  path: /student/schedule/waitlist
  defaults: { _controller: KulaHEdSchedulingBundle:Schedule:waitlist }

sis_HEd_offering_sections:
  path: /offering/sections
  defaults: { _controller: KulaHEdSchedulingBundle:Section:index }

sis_HEd_offering_sections_add:
  path: /offering/section/add
  defaults: { _controller: KulaHEdSchedulingBundle:Section:add }
  methods: [GET]

sis_HEd_offering_sections_create:
  path: /offering/section/add
  defaults: { _controller: KulaHEdSchedulingBundle:Section:create }
  methods: [POST]

sis_HEd_offering_sections_delete:
  path: /offering/section/delete
  defaults: { _controller: KulaHEdSchedulingBundle:Section:delete }
  methods: [POST]

sis_HEd_offering_sections_grades:
  path: /offering/section/grades
  defaults: { _controller: KulaHEdSchedulingBundle:Section:grades }

sis_HEd_offering_sections_inactivate:
  path: /offering/sections/inactivate
  defaults: { _controller: KulaHEdSchedulingBundle:Section:inactivate }
  methods: [POST]

sis_HEd_offering_sections_report_classroster_generate:
  path: /offering/section/reports/roster/generate
  defaults: { _controller: KulaHEdSchedulingBundle:ClassRosterReport:generate }
  methods: [POST]

sis_HEd_offering_sections_reports_classroster:
  path: /offering/sections/reports/classroster
  defaults: { _controller: KulaHEdSchedulingBundle:ClassRosterReport:index }

sis_HEd_offering_sections_reports_masterschedule:
  path: /offering/sections/reports/masterschedule
  defaults: { _controller: KulaHEdSchedulingBundle:MasterScheduleReport:index }
  methods: [GET]

sis_HEd_offering_sections_reports_masterschedule_generate:
  path: /offering/section/reports/masterschedule
  defaults: { _controller: KulaHEdSchedulingBundle:MasterScheduleReport:generate }
  methods: [POST]

sis_HEd_offering_sections_roster:
  path: /offering/section/roster
  defaults: { _controller: KulaHEdSchedulingBundle:Section:roster }

sis_HEd_offering_sections_waitlist:
  path: /offering/sections/waitlist
  defaults: { _controller: KulaHEdSchedulingBundle:Section:waitlist }

sis_HEd_offering_staff_reports_schedule:
  path: /offering/staff/reports/schedule
  defaults: { _controller: KulaHEdSchedulingBundle:StaffScheduleReport:index }
  methods: [GET]

sis_HEd_offering_staff_schedule_reports_staffschedule_generate:
  path: /offering/staff/reports/schedule
  defaults: { _controller: KulaHEdSchedulingBundle:StaffScheduleReport:generate }
  methods: [POST]

sis_HEd_offering_sections_recalculateSectionTotals:
  path: /offering/sections/recalculateTotals
  defaults: { _controller: KulaHEdSchedulingBundle:Section:recalculate_section_totals }

sis_HEd_offering_sections_courses:
  path: /offering/sections/courses
  defaults: { _controller: KulaHEdSchedulingBundle:Section:courses }

sis_HEd_offering_sections_staff:
  path: /offering/sections/staff
  defaults: { _controller: KulaHEdSchedulingBundle:Section:staff }

sis_HEd_course_chooser:
  path: /offering/course/chooser
  defaults: { _controller: KulaHEdSchedulingBundle:Courses:chooser }

sis_HEd_courses:
  path: /offering/courses
  defaults: { _controller: KulaHEdSchedulingBundle:Courses:index }

sis_HEd_courses_add:
  path: /offering/courses/add
  defaults: { _controller: KulaHEdSchedulingBundle:Courses:add }
  methods: [GET]

sis_HEd_courses_books:
  path: /offering/courses/books
  defaults: { _controller: KulaHEdSchedulingBundle:Books:books }

sis_HEd_courses_corequisites:
  path: /offering/courses/corequisites
  defaults: { _controller: KulaHEdSchedulingBundle:Courses:corequisites }

sis_HEd_courses_create:
  path: /offering/courses/add
  defaults: { _controller: KulaHEdSchedulingBundle:Courses:create }
  methods: [POST]

sis_HEd_courses_delete:
  path: /offering/courses/delete
  defaults: { _controller: KulaHEdSchedulingBundle:Courses:delete }
  methods: [POST]

sis_HEd_courses_fees:
  path: /offering/courses/fees
  defaults: { _controller: KulaHEdSchedulingBundle:CourseFees:index }

sis_HEd_courses_prerequisites:
  path: /offering/courses/prerequisites
  defaults: { _controller: KulaHEdSchedulingBundle:Courses:prerequisites }

sis_HEd_degrees_degrees:
  path: /offering/degrees/degrees
  defaults: { _controller: KulaHEdSchedulingBundle:Degree:degrees }

sis_HEd_degrees_majors:
  path: /offering/degrees/majors
  defaults: { _controller: KulaHEdSchedulingBundle:Degree:majors }

sis_HEd_degrees_minors:
  path: /offering/degrees/minors
  defaults: { _controller: KulaHEdSchedulingBundle:Degree:minors }

sis_HEd_degrees_concentrations:
  path: /offering/degrees/concentrations
  defaults: { _controller: KulaHEdSchedulingBundle:Degree:concentrations }

sis_HEd_degrees_requirements_groups:
  path: /offering/degrees/requirements/groups/{type}/{id}
  defaults: { _controller: KulaHEdSchedulingBundle:Requirements:requirement_groups }

sis_HEd_degrees_requirements_groups_courses:
  path: /offering/degrees/requirements/courses/{id}
  defaults: { _controller: KulaHEdSchedulingBundle:Requirements:requirement_group_courses }

sis_HEd_degrees_requirements_groups_courses_equiv:
  path: /offering/degrees/requirements/courses/equivalent/{id}
  defaults: { _controller: KulaHEdSchedulingBundle:Requirements:requirement_group_courses_equivalent }

sis_HEd_room_chooser:
  path: /offering/room/chooser
  defaults: { _controller: KulaHEdSchedulingBundle:Rooms:chooser }
  methods: [GET]

sis_HEd_rooms:
  path: /offering/rooms
  defaults: { _controller: KulaHEdSchedulingBundle:Rooms:index }