Teacher_HEd_Roster:
  path: /class/roster
  defaults: 
    _controller: KulaHEdSchedulingBundle:TeacherSection:roster
    _navigation: Teacher.HEd.Roster.Current

Teacher_HEd_Roster_Dropped:
  path: /class/roster/dropped
  defaults: 
    _controller: KulaHEdSchedulingBundle:TeacherSection:dropped_roster
    _navigation: Teacher.HEd.Roster.Dropped

Teacher_HEd_Reports_ClassRoster:
  path: /class/reports/class_roster
  defaults: 
    _controller: KulaHEdSchedulingBundle:TeacherClassRosterReport:index
    _navigation: Teacher.HEd.Roster.ClassRoster
  methods: [GET]

Teacher_HEd_Reports_ClassRoster_Generate:
  path: /class/reports/class_roster
  defaults: { _controller: KulaHEdSchedulingBundle:TeacherClassRosterReport:generate }
  methods: [POST]

Teacher_HEd_Student_Schedule:
  path: /student/schedule
  defaults: 
    _controller: KulaHEdSchedulingBundle:TeacherStudentSchedule:index
    _navigation: Teacher.HEd.Advisee.Schedule