HEd.Billing.Code.Type:
  description: "Billing Code Types"
  allow_update: false
  values:
    - { code: C, description: "Charge" }
    - { code: P, description: "Payment" }

HEd.Billing.Fee.Discount:
  description: "Billing Discounts"
  allow_update: true
