Core_HEd_Billing_StudentBilling_Balances:
  path: /core/HEd/billing/student/balances
  defaults: 
    _controller: KulaHEdBillingBundle:CoreBilling:balances
    _navigation: Core.HEd.Billing.StudentBilling.Balances

Core_HEd_Billing_StudentBilling_AddCharge:
  path: /core/HEd/billing/student/charges/add
  defaults: 
    _controller: KulaHEdBillingBundle:CoreTransactions:add_charge
    _navigation: Core.HEd.Billing.StudentBilling

Core_HEd_Billing_StudentBilling_History:
  path: /core/HEd/billing/student/history
  defaults: 
    _controller: KulaHEdBillingBundle:CoreTransactions:history
    _navigation: Core.HEd.Billing.StudentBilling.History

Core_HEd_Billing_StudentBilling_AddPayment:
  path: /core/HEd/billing/student/payments/add
  defaults: 
    _controller: KulaHEdBillingBundle:CoreTransactions:add_payment
    _navigation: Core.HEd.Billing.StudentBilling

Core_HEd_Billing_Reports_BillingLedger:
  path: /core/HEd/billing/reports/billing_ledger
  defaults: 
    _controller: KulaHEdBillingBundle:CoreBillingConstituentLedgerReport:index
    _navigation: Core.HEd.Billing.Reports.BillingLedger
  methods: [GET]

Core_HEd_Billing_Reports_BillingLedger_Generate:
  path: /core/HEd/billing/reports/billing_ledger
  defaults: { _controller: KulaHEdBillingBundle:CoreBillingConstituentLedgerReport:generate }
  methods: [POST]

Core_HEd_Billing_Reports_BillingReceipt:
  path: /core/HEd/billing/reports/billing_receipt
  defaults: 
    _controller: KulaHEdBillingBundle:CoreBillingReceiptReport:index
    _navigation: Core.HEd.Billing.Reports.BillingReceipt
  methods: [GET]

Core_HEd_Billing_Reports_BillingReceipt_Generate:
  path: /core/HEd/billing/reports/billing_receipt
  defaults: { _controller: KulaHEdBillingBundle:CoreBillingReceiptReport:generate }
  methods: [POST]

Core_HEd_Billing_Reports_BillingStatement:
  path: /core/HEd/billing/reports/billing_statement
  defaults: 
    _controller: KulaHEdBillingBundle:CoreBillingStatementReport:index
    _navigation: Core.HEd.Billing.Reports.BillingStatement
  methods: [GET]

Core_HEd_Billing_Reports_BillingStatement_Generate:
  path: /core/HEd/billing/reports/billing_statement
  defaults: { _controller: KulaHEdBillingBundle:CoreBillingStatementReport:generate }
  methods: [POST]

Core_HEd_Billing_StudentBilling_TransactionDetail:
  path: /core/HEd/billing/student/transactions/{constituent_transaction_id}/detail
  defaults: { _controller: KulaHEdBillingBundle:CoreTransactions:transaction_detail }

Core_HEd_Billing_StudentBilling_Transactions:
  path: /core/HEd/billing/student/transactions
  defaults: 
    _controller: KulaHEdBillingBundle:CoreTransactions:transactions
    _navigation: Core.HEd.Billing.StudentBilling.Transactions

Core_HEd_Billing_Billing_Pending:
    path:     /core/HEd/billing/billing/pending
    defaults: 
      _controller: KulaHEdBillingBundle:CoreHomeBilling:pending
      _navigation: Core.HEd.Billing.Billing.Pending

Core_HEd_Billing_Billing_AllPending:
    path:     /core/HEd/billing/billing/pending/all
    defaults: 
      _controller: KulaHEdBillingBundle:CoreHomeBilling:all_pending
      _navigation: Core.HEd.Billing.Billing.AllPending

Core_HEd_Billing_Reports_StudentStatement:
  path: /core/HEd/billing/reports/student_statement
  defaults: 
    _controller: KulaHEdBillingBundle:CoreStudentStatementReport:index
    _navigation: Core.HEd.Billing.Reports.StudentStatement
  methods: [GET]

Core_HEd_Billing_BillingSetup_Codes:
  path: /core/HEd/billing/setup/codes
  defaults: 
    _controller: KulaHEdBillingBundle:CoreCodes:codes
    _navigation: Core.HEd.Billing.BillingSetup.Codes

Core_HEd_Billing_BillingSetup_TuitionRates:
  path: /core/HEd/billing/setup/tuition_rates
  defaults: 
    _controller: KulaHEdBillingBundle:CoreTuitionRates:index
    _navigation: Core.HEd.Billing.BillingSetup.TuitionRates

Core_HEd_Billing_BillingSetup_TuitionRates_Transactions:
  path: /core/HEd/billing/setup/tuition_rates/{tuition_rate_id}/transactions
  defaults: 
    _controller: KulaHEdBillingBundle:CoreTuitionRates:transactions
    _navigation: Core.HEd.Billing.BillingSetup.TuitionRates

Core_HEd_Billing_BillingSetup_TuitionRates_Students:
  path: /core/HEd/billing/setup/tuition_rates/{tuition_rate_id}/students
  defaults: 
    _controller: KulaHEdBillingBundle:CoreTuitionRates:students
    _navigation: Core.HEd.Billing.BillingSetup.TuitionRates

Core_HEd_Billing_BillingSetup_TuitionRates_Refunds:
  path: /core/HEd/billing/setup/tuition_rates/{tuition_rate_id}/refunds
  defaults: 
    _controller: KulaHEdBillingBundle:CoreTuitionRates:refunds
    _navigation: Core.HEd.Billing.BillingSetup.TuitionRates

Core_HEd_Billing_BillingSetup_TuitionRates_Transactions_Refunds:
  path: /core/HEd/billing/setup/tuition_rates/{tuition_rate_id}/transactions/{transaction_id}/refunds
  defaults: 
    _controller: KulaHEdBillingBundle:CoreTuitionRates:transactionRefunds
    _navigation: Core.HEd.Billing.BillingSetup.TuitionRates


Core_HEd_Course_Course_Fees:
  path: /core/HEd/course/course/fees
  defaults: 
    _controller: KulaHEdBillingBundle:CoreCourseFees:index
    _navigation: Core.HEd.Course.Course.Fees

Core_HEd_Scheduling_Section_Fees:
  path: /core/HEd/scheduling/sections/fees
  defaults: 
    _controller: KulaHEdBillingBundle:CoreCourseFees:sectionFees
    _navigation: Core.HEd.Scheduling.Section.Fees