_HEd_scheduling_core:
    resource: "@KulaHEdBillingBundle/Resources/config/routing/core.yml"
    prefix: core/HEd

_HEd_scheduling_api:
    resource: "@KulaHEdBillingBundle/Resources/config/routing/api.yml"
    prefix: api/HEd
