K12.Student.EmergencyContact:
  description: "Student Emergency Contacts"
  db_table_name: STUD_STUDENT_EMERGENCY_CONTACT
  timestamps: true
  fields:
    ID:
      description: "ID"
      primary: true
      db_column_name: EMERGENCY_CONTACT_ID
      db_column_type: primary_serial
      column_name: "Emergency Contact ID"
      label_name: "Emergency Contact ID"
    StudentID:
      description: "Student ID"
      parent: K12.Student.ID
      db_column_name: STUDENT_ID
      db_column_type: serial
      column_name: "Student ID"
      label_name: "Student ID"
    Sort:
      description: "Sort"
      db_column_name: SORT
      db_column_type: int
      db_column_size: tiny
      db_column_null: true
      field_type: text
      field_size: 5
      column_name: "Sort"
      label_name: "Sort"
    Name:
      description: "Emergency Contact Name"
      db_column_name: EMERGENCY_CONTACT_NAME
      db_column_type: varchar
      db_column_length: 50
      db_column_null: true
      field_type: text
      field_size: 20
      column_name: "Emergency Contact Name"
      label_name: "Emergency Contact Name"
    Relationship:
      description: "Relationship"
      db_column_name: RELATIONSHIP
      db_column_type: varchar
      db_column_length: 5
      db_column_null: true
      field_type: lookup
      lookup: K12.Student.EmergencyContact.Relationship.Type
      column_name: "Relationship"
      label_name: "Relationship"
    Phone:
      description: "Emergency Contact Phone"
      db_column_name: EMERGENCY_CONTACT_PHONE
      db_column_type: varchar
      db_column_length: 15
      db_column_null: true
      field_type: text
      field_size: 15
      column_name: "Emergency Contact Phone"
      label_name: "Emergency Contact Phone"
    Email:
      description: "Emergency Contact EMAIL"
      db_column_name: EMERGENCY_CONTACT_EMAIL
      db_column_type: varchar
      db_column_length: 255
      db_column_null: true
      field_type: text
      field_size: 25
      column_name: "Emergency Contact Email"
      label_name: "Email"
    AuthorizedDriver:
      description: "Authorized Driver Phone"
      db_column_name: AUTHORIZED_DRIVER
      db_column_type: bool
      db_column_null: false
      db_column_default: 0
      field_type: checkbox
      column_name: "Authorized Driver"
      label_name: "Authorized Driver"