sis_core_constituent_constituent:
    path:     /core/constituent/constituent
    defaults: { _controller: KulaCoreConstituentBundle:Constituent:index }
    
sis_core_constituent_chooser:
    path: /core/constituent/chooser
    defaults: { _controller: KulaCoreConstituentBundle:Constituent:chooser }

sis_core_constituent_combiner:
    path:     /core/constituent/combiner
    defaults: { _controller: KulaCoreConstituentBundle:Constituent:combine }