HEd.Student.Class:
  description: "Classes"
  db_table_name: STUD_STUDENT_CLASSES
  timestamps: true
  fields:
    ID:
      description: "ID"
      primary: true
      db_column_name: STUDENT_CLASS_ID
      db_column_type: primary_serial
      column_name: "Student Class ID"
      label_name: "Student Class ID"
    StudentStatusID:
      description: "Student Status ID"
      parent: HEd.Student.Status.ID
      db_column_name: STUDENT_STATUS_ID
      db_column_type: serial
      column_name: "Student Status ID"
      label_name: "Student Status ID"
    SectionID:
      description: "Section ID"
      parent: HEd.Section.ID
      db_column_name: SECTION_ID
      db_column_type: serial
      field_type: multicheckbox
      column_name: "Section ID"
      label_name: "Section ID"
    CourseID:
      description: "Course ID"
      parent: HEd.Course.ID
      db_column_name: COURSE_ID
      db_column_type: serial
      db_column_null: true
      field_type: chooser
      chooser: HEd.Course
      column_name: "Course ID"
      label_name: "Course ID"
    StartDate:
      description: "Start Date"
      db_column_name: START_DATE
      db_column_type: date
      db_column_null: true
      field_type: date
      column_name: "Start Date"
      label_name: "Start Date"
    EndDate:
      description: "End Date"
      db_column_name: END_DATE
      db_column_type: date
      db_column_null: true
      field_type: date
      column_name: "End Date"
      label_name: "End Date"
    Level:
      description: "Level"
      db_column_name: LEVEL
      db_column_type: varchar
      db_column_length: 5
      db_column_null: true
      field_type: lookup
      lookup: HEd.Student.Enrollment.Level
      column_name: "Level"
      label_name: "Level"
    CreditsAttempted:
      description: "Credits Attempted"
      db_column_name: CREDITS_ATTEMPTED
      db_column_type: numeric
      db_column_length: 10
      db_column_precision: 3
      db_column_null: true
      field_type: text
      field_size: 6
      column_name: "Credits Attempted"
      label_name: "Credits Attempted"
    Dropped:
      description: "Dropped"
      db_column_name: DROPPED
      db_column_type: bool
      db_column_default: 0
      db_column_null: false
      field_type: checkbox
      column_name: "Dropped"
      label_name: "Dropped"
    DropDate:
      description: "Drop Date"
      db_column_name: DROP_DATE
      db_column_type: date
      db_column_null: true
      field_type: date
      column_name: "Drop Date"
      label_name: "Drop Date"
    ChangeReason:
      description: "Change Reason"
      db_column_name: CHANGE_REASON
      db_column_type: varchar
      db_column_length: 5
      db_column_null: true
      field_type: lookup
      lookup: HEd.Schedule.ChangeReason
      column_name: "Change Reason"
      label_name: "Change Reason"
    ChangeNotes:
      description: "Change Notes"
      db_column_name: CHANGE_NOTES
      db_column_type: text
      db_column_null: true
      field_type: textarea
      column_name: "Change Notes"
      label_name: "Change Notes"
    Priority:
      description: "Priority"
      db_column_name: PRIORITY
      db_column_type: int
      db_column_size: tiny
      db_column_null: true
      field_type: text
      field_size: 3
      column_name: "Priority"
      label_name: "Priority"
    RegistrationType:
      description: "Registration Type"
      db_column_name: REGISTRATION_TYPE
      db_column_type: varchar
      db_column_length: 5
      db_column_null: true
      field_type: lookup
      lookup: HEd.Schedule.RegistrationType
      column_name: "Registration Type"
      label_name: "Registration Type"    
    BillingStatus:
      description: "Billing Status"
      db_column_name: BILLING_STATUS
      db_column_type: varchar
      db_column_length: 5
      db_column_null: true
      field_type: lookup
      lookup: HEd.Schedule.BillingStatus
      column_name: "Billing Status"
      label_name: "Billing Status"
    Paid:
      description: "Paid"
      db_column_name: PAID
      db_column_type: bool
      db_column_default: 0
      db_column_null: false
      field_type: checkbox
      column_name: "Paid"
      label_name: "Paid"
    Discount:
      description: "Discount"
      field_type: select
      class: Kula\Core\Bundle\BillingBundle\Field\SectionDiscount
      column_name: "Discount"
      label_name: "Discount"
    DiscountProof:
      description: "Discount Proof"
      field_type: text
      field_size: 15
      column_name: "Discount Proof"
      label_name: "Discount Proof"