HEd.Student.WaitList:
  description: "Wait List"
  db_table_name: STUD_STUDENT_WAIT_LIST
  timestamps: true
  fields:
    ID:
      description: "ID"
      primary: true
      db_column_name: STUDENT_WAIT_LIST_ID
      db_column_type: primary_serial
      column_name: "Student Wait List ID"
      label_name: "Student Wait List ID"
    StudentStatusID:
      description: "Student Status ID"
      parent: HEd.Student.Status.ID
      db_column_name: STUDENT_STATUS_ID
      db_column_type: serial
      column_name: "Student Status ID"
      label_name: "Student Status ID"
    SectionID:
      description: "Section ID"
      parent: HEd.Section.ID
      db_column_name: SECTION_ID
      db_column_type: serial
      field_type: multicheckbox
      column_name: "Section ID"
      label_name: "Section ID"
    AddedTimestamp:
      description: "Added Timestamp"
      db_column_name: ADDED_TIMESTAMP
      db_column_type: datetime
      field_type: datetime
      column_name: "Added Timestamp"
      label_name: "Added Timestamp"