Core.HEd.Student:
  description: "Student Higher Education"
  display_name: "Student"
  type: dir
  parent: Core.HEd
  forms: 
    Information:
      description: "Information"
      display_name: "Information"
      tabs:
        Basic:
          description: "Basic"
          display_name: "Basic"
          route: core_HEd_student_information_basic
        Demographic:
          description: "Demographic"
          display_name: "Demographic"
          route: core_HEd_student_information_demographic
        Addresses:
          description: "Addresses"
          display_name: "Addresses"
          route: core_HEd_student_information_addresses
        Phones:
          description: "Phones"
          display_name: "Phones"
          route: core_HEd_student_information_phones
        EmailAddresses:
          description: "Email Addresses"
          display_name: "Email Addresses"
          route: core_HEd_student_information_emailaddres
        EmergencyContacts:
          description: "Emergency Contacts"
          display_name: "Emergency Contacts"
          route: core_HEd_student_information_emergencycontacts
        Other:
          description: "Other Information"
          display_name: "Other Info"
          route: core_HEd_student_information_otherinfo
      button_add:
        route: core_HEd_student_information_add
      menu_actions:
        NewAddress:
          description: "New Address"
          display_name: "New Address"
          divider_before: true
          record_loaded: true
          route: core_HEd_student_information_addresses_add
    Enrollment:
      description: "Enrollment"
      display_name: "Enrollment"
      tabs:
        Statuses:
          display_name: "Statuses"
          description: "Statuses"
          route: core_HEd_student_enrollment_statuses
      menu_actions:
        ActivateInactivate:
          description: "Activate/Inactivate"
          display_name: "Activate/Inactivate"
          record_loaded: true
          route: core_HEd_student_enrollment_activateinactivate
        Edit:
          description: "Edit Enrollment"
          display_name: "Edit Enrollment"
          record_loaded: true
          route: core_HEd_student_enrollment_edit
      menu_reports:
        EnrollmentVerification:
          description: "Enrollment Verification"
          display_name: "Enrollment Verification"
          route: core_HEd_student_enrollment_reports_enrollmentverification
    Documents:
      original: Core.HEd.Documents.StudentDocuments
      display_name: "Documents"
    Holds:
      original: Core.HEd.Holds.StudentHolds
      display_name: "Holds"

Core.HEd.Documents:
  type: dir
  parent: Core.HEd
  description: "Documents"
  display_name: "Documents"
  forms:
    DocumentsSetup:
      description: "Documents Setup"
      display_name: "Documents Setup"
      route: core_HEd_setup_student_documents
    StudentDocuments:
      description: "Student Documents"
      display_name: "Student Documents"
      route: core_HEd_student_documents

Core.HEd.Holds:
  type: dir
  parent: Core.HEd
  description: "Holds"
  display_name: "Holds"
  forms:
    Holds:
      description: "Holds"
      display_name: "Holds"
      route: core_HEd_home_holds
    StudentHolds:
      description: "Student Holds"
      display_name: "Student Holds"
      route: core_HEd_student_holds
    HoldsSetup:
      description: "Holds Setup"
      display_name: "Holds Setup"
      route: core_HEd_setup_student_holds

Core.HEd.Student.Reports:
  type: dir
  parent: Core.HEd.Student
  description: "Reports"
  display_name: "Reports"
  reports:
    EnrollmentVerification:
      description: "Enrollment Verification"
      display_name: "Enrollment Verification"
      route: core_HEd_student_enrollment_reports_enrollmentverification