SIS.HEd.Student:
  description: "Student Higher Education"
  display_name: "Student (HEd)"
  type: form_group
  portal: sis
  sort: 1
  forms: 
    Information:
      description: "Information"
      display_name: "Information"
      sort: 1
      tabs:
        Basic:
          description: "Basic"
          display_name: "Basic"
          sort: 1
          route: sis_HEd_student_information_basic
        Demographic:
          description: "Demographic"
          display_name: "Demographic"
          sort: 2
          route: sis_HEd_student_information_demographic
        Enrollment:
          description: "Enrollment"
          display_name: "Enrollment"
          sort: 3
          route: sis_HEd_student_information_enrollment
        Addresses:
          description: "Addresses"
          display_name: "Addresses"
          sort: 4
          route: sis_HEd_student_information_addresses
        Phones:
          description: "Phones"
          display_name: "Phones"
          sort: 5
          route: sis_HEd_student_information_phones
        EmailAddresses:
          description: "Email Addresses"
          display_name: "Email Addresses"
          sort: 6
          route: sis_HEd_student_information_emailaddres
        EmergencyContacts:
          description: "Emergency Contacts"
          display_name: "Emergency Contacts"
          sort: 7
          route: sis_HEd_student_information_emergencycontacts
        Other:
          description: "Other Information"
          display_name: "Other Info"
          sort: 8
          route: sis_HEd_student_information_otherinfo
      menu_actions:
        NewStudent:
          description: "New Student"
          display_name: "New Student"
          route: sis_HEd_student_information_add
          sort: 1
        NewAddress:
          description: "New Address"
          display_name: "New Address"
          divider_before: true
          record_loaded: true
          route: sis_HEd_student_information_addresses_add
          sort: 2
    Enrollment:
      description: "Enrollment"
      display_name: "Enrollment"
      sort: 2
      menu_actions:
        ActivateInactivate:
          description: "Activate/Inactivate"
          display_name: "Activate/Inactivate"
          record_loaded: true
          route: sis_HEd_student_enrollment_activateinactivate
          sort: 1
      menu_reports:
        EnrollmentVerification:
          description: "Enrollment Verification"
          display_name: "Enrollment Verification"
          route: sis_HEd_student_enrollment_reports_enrollmentverification
          sort: 1
    Documents:
      description: "Documents"
      display_name: "Documents"
      route: sis_HEd_student_documents
      sort: 7
    Holds:
      description: "Holds"
      display_name: "Holds"
      route: sis_HEd_student_holds
      sort: 8
  reports:
    EnrollmentVerification:
      description: "Enrollment Verification"
      display_name: "Enrollment Verification"
      route: sis_HEd_student_enrollment_reports_enrollmentverification
      sort: 1
SIS.Home:
  description: "Home"
  display_name: "Home"
  type: form_group
  portal: sis
  sort: 1
  forms: 
    Holds:
      description: "Holds"
      display_name: "Holds"
      route: sis_HEd_home_holds
      sort: 1