Core.HEd.Student:
  description: "Student Higher Education"
  display_name: "Student"
  type: dir
  parent: Core.HEd
  forms: 
    Information:
      description: "Information"
      display_name: "Information"
      tabs:
        Basic:
          description: "Basic"
          display_name: "Basic"
          route: core_HEd_student_information_basic
        Demographic:
          description: "Demographic"
          display_name: "Demographic"
          route: core_HEd_student_information_demographic
        Parents:
          description: "Parents"
          display_name: "Parents"
          route: core_HEd_student_information_parents
        Addresses:
          description: "Addresses"
          display_name: "Addresses"
          route: core_HEd_student_information_addresses
        Phones:
          description: "Phones"
          display_name: "Phones"
          route: core_HEd_student_information_phones
        EmailAddresses:
          description: "Email Addresses"
          display_name: "Email Addresses"
          route: core_HEd_student_information_emailaddres
        EmergencyContacts:
          description: "Emergency Contacts"
          display_name: "Emergency Contacts"
          route: core_HEd_student_information_emergencycontacts
        Other:
          description: "Other Information"
          display_name: "Other Info"
          route: core_HEd_student_information_otherinfo
        User:
          description: "User Information"
          display_name: "User Info"
          route: core_HEd_student_information_userinfo
      button_add:
        route: core_HEd_student_information_add
      menu_actions:
        NewAddress:
          description: "New Address"
          display_name: "New Address"
          record_loaded: true
          route: core_HEd_student_information_addresses_add
        NewParent:
          description: "New Parent"
          display_name: "New Parent"
          divider_before: true
          record_loaded: true
          route: core_HEd_student_information_parents_add
    Enrollment:
      description: "Enrollment"
      display_name: "Enrollment"
      tabs:
        Statuses:
          display_name: "Statuses"
          description: "Statuses"
          route: core_HEd_student_enrollment_statuses
      menu_actions:
        ActivateInactivate:
          description: "Activate/Inactivate"
          display_name: "Activate/Inactivate"
          record_loaded: true
          route: core_HEd_student_enrollment_activateinactivate
        Edit:
          description: "Edit Enrollment"
          display_name: "Edit Enrollment"
          record_loaded: true
          route: core_HEd_student_enrollment_edit
      menu_reports:
        EnrollmentVerification:
          description: "Enrollment Verification"
          display_name: "Enrollment Verification"
          route: core_HEd_student_enrollment_reports_enrollmentverification
    Parent:
      description: "Parent"
      display_name: "Parent"
      tabs:
        Basic:
          description: "Basic"
          display_name: "Basic"
          route: core_HEd_student_parent_basic
        Children:
          description: "Children"
          display_name: "Children"
          route: core_HEd_student_parent_children
        Addresses:
          description: "Addresses"
          display_name: "Addresses"
          route: core_HEd_student_parent_addresses
        Phones:
          description: "Phones"
          display_name: "Phones"
          route: core_HEd_student_parent_phones
        EmailAddresses:
          description: "Email Addresses"
          display_name: "Email Addresses"
          route: core_HEd_parent_EmailAddresses
      menu_actions:
        NewAddress:
          description: "New Address"
          display_name: "New Address"
          record_loaded: true
          route: core_HEd_student_parent_addresses_add
      button_delete:
        route: core_HEd_student_parent_delete
    Documents:
      original: Core.HEd.Documents.StudentDocuments
      display_name: "Documents"
    Holds:
      original: Core.HEd.Holds.StudentHolds
      display_name: "Holds"
    Forms:
      original: Core.HEd.Forms.StudentForms
      display_name: "Forms"
    Schedule:
      description: "Schedule"
      display_name: "Schedule"
      tabs:
        CurrentSchedule:
          description: "Current Schedule"
          display_name: "Current Schedule"
          route: Core_HEd_Scheduling_StudentSchedule
        History:
          description: "History"
          display_name: "History"
          route: Core_HEd_Scheduling_StudentSchedule_History
        WaitList:
          description: "Wait List"
          display_name: "Wait List"
          route: Core_HEd_Scheduling_StudentSchedule_WaitList
      menu_actions:
        AddClasses:
          description: "Add Classes"
          display_name: "Add Classes"
          record_loaded: true
          route: Core_HEd_Scheduling_StudentSchedule_Add
        CalculateFTEAndTuition:
          description: "Calculate FTE and Tuition"
          display_name: "Calculate FTE & Tuition"
          divider_before: true
          route: Core_HEd_Scheduling_StudentSchedule_CalculateTotals
      menu_reports:
        StudentSchedule:
          description: "Student Schedule"
          display_name: "Student Schedule"
          route: Core_HEd_Scheduling_Reports_StudentSchedule
        StudentScheduleBill:
          description: "Student Schedule & Bill"
          display_name: "Student Schedule & BIll"
          route: Core_HEd_Scheduling_Reports_StudentScheduleBill
    CourseHistory:
      description: "Course History"
      display_name: "Course History"
      tabs:
        CourseHistory:
          description: "Course History"
          display_name: "Course History"
          route: Core_HEd_Grading_StudentCourseHistory_CourseHistory
        Degrees:
          description: "Degrees"
          display_name: "Degrees"
          route: Core_HEd_Grading_StudentCourseHistory_Degrees
        Standings:
          description: "Standings"
          display_name: "Standings"
          route: Core_HEd_Grading_StudentCourseHistory_Standings
        TranscriptComments:
          description: "Transcript Comments"
          display_name: "Transcript Comments"
          route: Core_HEd_Grading_StudentCourseHistory_TranscriptComments
        Terms:
          description: "Terms"
          display_name: "Terms"
          route: Core_HEd_Grading_StudentCourseHistory_Terms
        Transcript:
          description: "Transcript"
          display_name: "Transcript"
          route: Core_HEd_Grading_StudentCourseHistory_Transcript
        DegreeAudit:
          description: "Degree Audit"
          display_name: "Degree Audit"
          route: Core_HEd_Grading_StudentCourseHistory_DegreeAudit
      menu_actions:
        RecalculateTermTotals:
          description: "Calculate Term Totals"
          display_name: "Calculate Term Totals"
          route: Core_HEd_Grading_StudentCourseHistory_CalculateTermTotals
      menu_reports:
        StudentTranscript:
          description: "Student Transcript"
          display_name: "Student Transcript"
          route: Core_HEd_Grading_Reports_StudentTranscript
        DegreeAuditReport:
          description: "Degree Audit"
          display_name: "Degree Audit"
          route: Core_HEd_Grading_Reports_DegreeAudit

Core.HEd.Documents:
  type: dir
  parent: Core.HEd
  description: "Documents"
  display_name: "Documents"
  forms:
    DocumentsSetup:
      description: "Documents Setup"
      display_name: "Documents Setup"
      route: core_HEd_setup_student_documents
    StudentDocuments:
      description: "Student Documents"
      display_name: "Student Documents"
      route: core_HEd_student_documents

Core.HEd.Holds:
  type: dir
  parent: Core.HEd
  description: "Holds"
  display_name: "Holds"
  forms:
    Holds:
      description: "Holds"
      display_name: "Holds"
      route: core_HEd_home_holds
    StudentHolds:
      description: "Student Holds"
      display_name: "Student Holds"
      route: core_HEd_student_holds
    HoldsSetup:
      description: "Holds Setup"
      display_name: "Holds Setup"
      route: core_HEd_setup_student_holds

Core.HEd.Forms:
  type: dir
  parent: Core.HEd
  description: "Forms"
  display_name: "Forms"
  forms:
    StudentForms:
      description: "Student Forms"
      display_name: "Student Forms"
      route: core_HEd_student_forms
    FormsSetup:
      description: "Forms Setup"
      display_name: "Forms Setup"
      route: core_HEd_setup_student_forms

Core.HEd.Student.Reports:
  type: dir
  parent: Core.HEd.Student
  description: "Reports"
  display_name: "Reports"
  reports:
    EnrollmentVerification:
      description: "Enrollment Verification"
      display_name: "Enrollment Verification"
      route: core_HEd_student_enrollment_reports_enrollmentverification

Core.Constituent.Combiner.StudentStatusHEd:
  parent: Core.Constituent.Combiner
  type: tab
  target: HEd
  description: "Student Status Combiner"
  display_name: "Student Status"
  route: Core_Constituent_Combiner_StudentStatus_HEd