SIS.Student:
  description: "Student"
  display_name: "Student"
  type: form_group
  portal: sis
  sort: 1
  forms: 
    HEd.Information:
      description: "Information"
      display_name: "Information"
      sort: 1
      tabs:
        Basic:
          description: "Basic"
          display_name: "Basic"
          sort: 1
          route: sis_HEd_student_information_basic
        Demographic:
          description: "Demographic"
          display_name: "Demographic"
          sort: 2
          route: sis_HEd_student_information_demographic
        Enrollment:
          description: "Enrollment"
          display_name: "Enrollment"
          sort: 3
          route: sis_HEd_student_information_enrollment
        Addresses:
          description: "Addresses"
          display_name: "Addresses"
          sort: 4
          route: sis_HEd_student_information_addresses
        Phones:
          description: "Phones"
          display_name: "Phones"
          sort: 5
          route: sis_HEd_student_information_phones
        EmailAddresses:
          description: "Email Addresses"
          display_name: "Email Addresses"
          sort: 6
          route: sis_HEd_student_information_emailaddres
        EmergencyContacts:
          description: "Emergency Contacts"
          display_name: "Emergency Contacts"
          sort: 7
          route: sis_HEd_student_information_emergencycontacts
      menu_actions:
        NewStudent:
          description: "New Student"
          display_name: "New Student"
          route: sis_HEd_student_information_add
          sort: 1
        NewAddress:
          description: "New Address"
          display_name: "New Address"
          divider_before: true
          record_loaded: true
          route: sis_HEd_student_information_addresses_add
          sort: 2