SIS.HEd.Hold:
  class: Kula\HEd\Bundle\StudentBundle\Record\SISHoldCodeRecord
SIS.HEd.Student:
  class: Kula\HEd\Bundle\StudentBundle\Record\SISStudentRecord
SIS.HEd.Student.Status:
  class: Kula\HEd\Bundle\StudentBundle\Record\SISStudentStatusRecord

Teacher.HEd.Advisor.Student:
  class: Kula\HEd\Bundle\StudentBundle\Record\TeacherAdvisorStudentRecord
  
Student.HEd.Student.Status:
  class: Kula\HEd\Bundle\StudentBundle\Record\StudentStudentStatusRecord