Core.HEd.Hold:
  class: Kula\HEd\Bundle\StudentBundle\Record\CoreHoldCodeRecord
Core.HEd.Student:
  class: Kula\HEd\Bundle\StudentBundle\Record\CoreStudentRecord
Core.HEd.Student.Status:
  class: Kula\HEd\Bundle\StudentBundle\Record\CoreStudentStatusRecord
Core.HEd.Parent:
  class: Kula\HEd\Bundle\StudentBundle\Record\CoreParentRecord

Teacher.HEd.Advisor.Student:
  class: Kula\HEd\Bundle\StudentBundle\Record\TeacherAdvisorStudentRecord
  
Student.HEd.Student:
  class: Kula\HEd\Bundle\StudentBundle\Record\StudentStudentRecord
Student.HEd.Student.Status:
  class: Kula\HEd\Bundle\StudentBundle\Record\StudentStudentStatusRecord