_HEd_student:
    resource: "@KulaHEdStudentBundle/Resources/config/routing/core.yml"
    prefix: core/HEd

_HEd_teacher:
    resource: "@KulaHEdStudentBundle/Resources/config/routing/teacher.yml"
    prefix: teacher/HEd