_HEd_student:
    resource: "@KulaHEdStudentBundle/Resources/config/routing/sis.yml"
    prefix: sis

_HEd_teacher:
    resource: "@KulaHEdStudentBundle/Resources/config/routing/teacher.yml"
    prefix: teacher