imports:
    - { resource: schema/student.yml }
    - { resource: schema/enrollment.yml }
    - { resource: schema/emergency.yml }
    - { resource: schema/document.yml }
    - { resource: schema/hold.yml }
    - { resource: schema/school.yml }