Core.Navigation.Type:
  description: "Navigation Types"
  allow_update: false
  values: 
    - { code: form_group, description: "From Group", sort: 1 }
    - { code: form, description: "Form", sort: 2 }
    - { code: menu_action, description: "Action Menu", sort: 3 }
    - { code: menu_report, description: "Report Menu", sort: 4 }
    - { code: tab, description: "Tab", sort: 5 }
    - { code: report_group, description: "Report Group", sort: 6 }
    - { code: report, description: "Report", sort: 7 }
Core.Navigation.Portal:
  description: "Portal List"
  allow_update: true
  values:
    - { code: core, description: "Core", sort: 1 }
    - { code: sis, description: "SIS", sort: 2 }
    - { code: teacher, description: "teacher", sort: 3 }
    - { code: student, description: "student", sort: 4 }