api_v1_children:
    path:     /user/current/children
    defaults: { _controller: KulaK12StudentBundle:APIv1Student:relatedChildren }
    methods: [GET]

api_v1_children_add:
    path:     /user/current/children/add
    defaults: { _controller: KulaK12StudentBundle:APIv1Student:createChild }
    methods: [POST]