Core_K12_Student_Student_Add:
  path: /student/student/add
  defaults: 
    _controller: KulaK12StudentBundle:CoreInformation:add
    _navigation: Core.K12.Student.Student

Core_K12_Student_Student_Add_Constituent:
  path: /student/student/add/constituent
  defaults: 
    _controller: KulaK12StudentBundle:CoreInformation:add_constituent
    _navigation: Core.K12.Student.Student
  methods: [GET]

Core_K12_Student_Student_Addresses:
  path: /student/student/addresses
  defaults: 
    _controller: KulaK12StudentBundle:CoreContactInfo:addresses
    _navigation: Core.K12.Student.Student.Addresses

Core_K12_Student_Student_Addresses_Detail:
  path: /student/student/{id}/addresses/detail/{sub_id}
  defaults: { _controller: KulaK12StudentBundle:CoreContactInfo:detail }

Core_K12_Student_Student_Basic:
  path: /student/student/basic
  defaults: 
    _controller: KulaK12StudentBundle:CoreInformation:basic
    _navigation: Core.K12.Student.Student.Basic

Core_K12_Student_Student_Create_Constituent:
  path: /student/student/add/constituent
  defaults: { _controller: KulaK12StudentBundle:CoreInformation:create_constituent }
  methods: [POST]

Core_K12_Student_Student_Demographic:
  path: /student/student/demographic
  defaults: 
    _controller: KulaK12StudentBundle:CoreInformation:demographic
    _navigation: Core.K12.Student.Student.Demographic
  
Core_K12_Student_Student_Parents:
  path: /student/student/parents
  defaults: 
    _controller: KulaK12StudentBundle:CoreParents:studentParents
    _navigation: Core.K12.Student.Student.Parents

Core_K12_Student_Student_Parents_Add:
  path: /student/student/parents/add
  defaults: 
    _controller: KulaK12StudentBundle:CoreParents:add
    _navigation: Core.K12.Student.Student.Parents
  
Core_K12_Student_Parents_Add_Constituent:
  path: /student/student/parents/add/constituent
  defaults: { _controller: KulaK12StudentBundle:CoreParents:add_constituent }
  methods: [GET]

Core_K12_Student_Parents_Create_Constituent:
  path: /student/student/parents/add/constituent
  defaults: { _controller: KulaK12StudentBundle:CoreParents:create_constituent }
  methods: [POST]

Core_K12_Student_Student_EmailAddresses:
  path: /student/student/email_addresses
  defaults:  
    _controller: KulaK12StudentBundle:CoreContactInfo:emailAddresses
    _navigation: Core.K12.Student.Student.EmailAddresses

Core_K12_Student_Student_EmergencyContacts:
  path: /student/student/emergency_contacts
  defaults: 
    _controller: KulaK12StudentBundle:CoreContactInfo:emergencyContacts
    _navigation: Core.K12.Student.Student.EmergencyContacts

Core_K12_Student_Enrollment_Edit:
  path: /student/enrollment/edit
  defaults: 
    _controller: KulaK12StudentBundle:CoreEnrollment:edit
    _navigation: Core.K12.Student.Enrollment

Core_K12_Student_Student_OtherInfo:
  path: /student/information/other_info
  defaults: 
    _controller: KulaK12StudentBundle:CoreInformation:other_info
    _navigation: Core.K12.Student.Student.Other

Core_K12_Student_Student_Phones:
  path: /student/student/phones
  defaults: 
    _controller: KulaK12StudentBundle:CoreContactInfo:phones
    _navigation: Core.K12.Student.Student.Phones

Core_K12_Student_Student_Addresses_Add:
  path: /student/student/addresses/add
  defaults: 
    _controller: KulaK12StudentBundle:CoreContactInfo:add_address
    _navigation: 

Core_K12_Student_Enrollment_ActivateInactivate:
  path: /student/enrollment/activate_inactivate
  defaults: 
    _controller: KulaK12StudentBundle:CoreEnrollment:activateinactivate
    _navigation: 

Core_K12_Student_Enrollment_ActivityDetail:
  path: /student/enrollment/activity/{student_enrollment_id}
  defaults: 
    _controller: KulaK12StudentBundle:CoreEnrollment:activity
    _navigation: 

Core_K12_Student_Enrollment_EnrollmentDetail:
  path: /student/enrollment/enrollments/{student_status_id}
  defaults: 
    _controller: KulaK12StudentBundle:CoreEnrollment:enrollments
    _navigation: 

Core_K12_Student_Parent_Basic:
  path: /student/parents
  defaults:
    _controller: KulaK12StudentBundle:CoreParent:index
    _navigation: 

Core_K12_Student_Parent_Children:
  path: /student/parents/children
  defaults: 
    _controller: KulaK12StudentBundle:CoreParent:children
    _navigation: 

Core_K12_Student_Parent_Delete:
  path: /student/parent/delete
  defaults: { _controller: KulaK12StudentBundle:CoreParent:delete }
  methods: [POST]

Core_K12_Student_Parent_Addresses:
  path: /student/parent/addresses
  defaults: 
    _controller: KulaK12StudentBundle:CoreParentsContactInfo:addresses
    _navigation: 

Core_K12_Student_Parent_Addresses_Detail:
  path: /student/parent/{id}/addresses/detail/{sub_id}
  defaults: 
    _controller: KulaK12StudentBundle:CoreParentsContactInfo:detail
    _navigation: 

Core_K12_Student_Parent_Addresses_Add:
  path: /student/parent/addresses/add
  defaults: 
    _controller: KulaK12StudentBundle:CoreParentsContactInfo:add_address
    _navigation: 

Core_K12_Student_Parent_Phones:
  path: /student/parent/phones
  defaults: 
    _controller: KulaK12StudentBundle:CoreParentsContactInfo:phones
    _navigation: Core.K12.Student.Parent.Phone
  
Core_K12_Student_Parent_EmailAddresses:
  path: /student/parent/email_addresses
  defaults: 
    _controller: KulaK12StudentBundle:CoreParentsContactInfo:emailAddresses
    _navigation: Core.K12.Student.Parent.EmailAddresses

Core_K12_Student_Enrollment_Statuses:
  path: /student/enrollment
  defaults: 
    _controller: KulaK12StudentBundle:CoreEnrollment:index
    _navigation: Core.K12.Student.Enrollment