parameters:
  kula.chooser.options.cache_class: kula%kernel.environment%ChooserCache

services:
  _defaults: { public: true }
  
  kula.core.chooser.cache:
    class: Kula\Core\Bundle\FrameworkBundle\CacheWarmer\ChooserCacheWarmer
    public: false
    arguments: ["@kula.core.chooser_store"]
    tags:
      - { name: kernel.cache_warmer }
  
  kula.core.chooser_store:
    class: Kula\Core\Component\Chooser\ChooserStore
    arguments: ["@kula.core.db", "%kula.chooser.options.cache_class%", "%kernel.cache_dir%", "%kernel.debug%", "@kernel", "@kula.core.session", "@kula.core.focus"] 
    public: false
    
  kula.core.chooser:
    class: Kula\Core\Component\Chooser\Chooser
    factory: ["@kula.core.chooser_store", getChoosers]
    arguments: ["@kula.core.db", "@kula.core.session", "@kula.core.focus"] 