services:
  symfony.AssetsInstallCommand:
      class: Symfony\Bundle\FrameworkBundle\Command\AssetsInstallCommand
      tags:
          -  { name: console.command }
  symfony.CacheClearCommand:
      class: Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand
      tags:
          -  { name: console.command }
  symfony.CacheWarmupCommand:
      class: Symfony\Bundle\FrameworkBundle\Command\CacheWarmupCommand
      tags:
          -  { name: console.command }
  symfony.ConfigDebugCommand:
      class: Symfony\Bundle\FrameworkBundle\Command\ConfigDebugCommand
      tags:
          -  { name: console.command }
  symfony.ConfigDumpReferenceCommand:
      class: Symfony\Bundle\FrameworkBundle\Command\ConfigDumpReferenceCommand
      tags:
          -  { name: console.command }
  symfony.ContainerDebugCommand:
      class: Symfony\Bundle\FrameworkBundle\Command\ContainerDebugCommand
      tags:
          -  { name: console.command }
  symfony.EventDispatcherDebugCommand:
      class: Symfony\Bundle\FrameworkBundle\Command\EventDispatcherDebugCommand
      tags:
          -  { name: console.command }
  symfony.RouterApacheDumperCommand:
      class: Symfony\Bundle\FrameworkBundle\Command\RouterApacheDumperCommand
      tags:
          -  { name: console.command }
  symfony.RouterDebugCommand:
      class: Symfony\Bundle\FrameworkBundle\Command\RouterDebugCommand
      tags:
          -  { name: console.command }
  symfony.RouterMatchCommand:
      class: Symfony\Bundle\FrameworkBundle\Command\RouterMatchCommand
      tags:
          -  { name: console.command }
  symfony.YamlLintCommand:
      class: Symfony\Bundle\FrameworkBundle\Command\YamlLintCommand
      tags:
          -  { name: console.command }