parameters:
  kula.navigation.options.cache_class: kula%kernel.environment%NavigationCache

services:
  kula.core.navigation.cache:
    class: Kula\Core\Bundle\FrameworkBundle\CacheWarmer\NavigationCacheWarmer
    public: false
    arguments: ["@kula.core.navigation_store"]
    tags:
      - { name: kernel.cache_warmer }
  
  kula.core.navigation_store:
    class: Kula\Core\Component\Navigation\NavigationStore
    arguments: ["@kula.core.db", "%kula.navigation.options.cache_class%", "%kernel.cache_dir%", "%kernel.debug%", "@kernel", "@kula.core.session", "@kula.core.permission", "@request_stack", "@kula.core.cache.kv"] 
    public: false
    
  kula.core.navigation:
    class: Kula\Core\Component\Navigation\Navigation
    factory: ["@kula.core.navigation_store", getNavigation]
    arguments: ["@kula.core.db", "@kula.core.cache.kv"] 