parameters:
  kula.organization.options.cache_class: kula%kernel.environment%OrganizationCache

services:
  kula.core.organization.cache:
    class: Kula\Core\Bundle\FrameworkBundle\CacheWarmer\OrganizationCacheWarmer
    public: false
    arguments: ["@kula.core.organization_store"]
    tags:
      - { name: kernel.cache_warmer }
  
  kula.core.organization_store:
    class: Kula\Core\Component\Focus\OrganizationStore
    arguments: ["@kula.core.db", %kula.organization.options.cache_class%, %kernel.cache_dir%, %kernel.debug%, "@kernel", "@request_stack", "@kula.core.cache.kv"] 
    public: false
    
  kula.core.organization:
    class: Kula\Core\Component\Focus\Organization
    factory_service: kula.core.organization_store
    factory_method: getOrganization
    arguments: ["@kula.core.cache.kv"]  