parameters:
  kula.record.options.cache_class: kula%kernel.environment%RecordCache

services:
  _defaults: { public: true }
  
  kula.core.record_type.cache:
    class: Kula\Core\Bundle\FrameworkBundle\CacheWarmer\RecordTypeCacheWarmer
    public: false
    arguments: ["@kula.core.record_type_store"]
    tags:
      - { name: kernel.cache_warmer }
  
  kula.core.record_type_store:
    class: Kula\Core\Component\Record\RecordTypesStore
    arguments: ["@kula.core.db", "%kula.record.options.cache_class%", "%kernel.cache_dir%", "%kernel.debug%", "@kernel"] 
    public: false
    
  kula.core.record_type:
    class: Kula\Core\Component\Record\RecordType
    factory: ["@kula.core.record_type_store", getRecordTypes]
    arguments: ["@kula.core.db"] 