parameters:
  kula.record.options.cache_class: kula%kernel.environment%RecordCache

services:
  kula.core.record.cache:
    class: Kula\Core\Bundle\FrameworkBundle\CacheWarmer\RecordCacheWarmer
    public: false
    arguments: ["@kula.core.record_store"]
    tags:
      - { name: kernel.cache_warmer }
  
  kula.core.record_store:
    class: Kula\Core\Component\Record\RecordStore
    arguments: ["@kula.core.db", %kula.record.options.cache_class%, %kernel.cache_dir%, %kernel.debug%] 
    public: false
    
  kula.core.record:
    class: Kula\Core\Component\Record\Record
    factory_service: kula.core.record_store
    factory_method: getRecord
    arguments: ["@kula.core.db"] 