parameters:
  kula.schema.options.cache_class: kula%kernel.environment%SchemaCache

services:
  kula.core.schema.cache:
    class: Kula\Core\Bundle\FrameworkBundle\CacheWarmer\SchemaCacheWarmer
    public: false
    arguments: ["@kula.core.schema_store"]
    tags:
      - { name: kernel.cache_warmer }
  
  kula.core.schema_store:
    class: Kula\Core\Component\Schema\SchemaStore
    arguments: ["@kula.core.db", "%kula.schema.options.cache_class%", "%kernel.cache_dir%", "%kernel.debug%", "@kernel", "@kula.core.cache.kv"] 
    public: false
    
  kula.core.schema:
    class: Kula\Core\Component\Schema\Schema
    factory: ["@kula.core.schema_store", getSchema]
    arguments: ["@kula.core.db", "@kula.core.cache.kv"] 