SIS.HEd.Student.Schedule:
  description: "Schedule"
  type: form
  portal: sis
  display_name: "Schedule"
  sort: 3
  tabs:
    CurrentSchedule:
      description: "Current Schedule"
      display_name: "Current Schedule"
      sort: 1
      route: sis_HEd_student_schedule
    History:
      description: "History"
      display_name: "History"
      sort: 2
      route: sis_HEd_student_schedule_history
    WaitList:
      description: "Wait List"
      display_name: "Wait List"
      sort: 4
      route: sis_HEd_student_schedule_waitlist
  menu_actions:
    AddClasses:
      description: "Add Classes"
      display_name: "Add Classes"
      sort: 1
      record_loaded: true
      route: sis_HEd_student_schedule_add
    CalculateFTEAndTuition:
      description: "Calculate FTE and Tuition"
      display_name: "Calculate FTE & Tuition"
      sort: 2
      divider_before: true
      record_loaded: true
      route: sis_HEd_student_schedule_calculateTotals
  menu_reports:
    StudentSchedule:
      description: "Student Schedule"
      display_name: "Student Schedule"
      sort: 1
      route: sis_HEd_student_schedule_reports_studentschedule

SIS.HEd.Reports.Student.StudentSchedule:
  description: "Student Schedule"
  type: report
  portal: sis
  display_name: "Student Schedule"
  sort: 5
  route: sis_HEd_student_schedule_reports_studentschedule

SIS.HEd.Academic:
  description: "Academic"
  display_name: "Academic (HEd)"
  portal: sis
  type: form_group
  sort: 3
  forms:
    Sections:
      description: "Sections"
      display_name: "Sections"
      sort: 1
      tabs:
        Basic:
          description: "Basic"
          display_name: "Basic"
          route: sis_HEd_offering_sections
          sort: 1
        Course:
          description: "Course"
          display_name: "Courses"
          route: sis_HEd_offering_sections_courses
          sort: 2
        Staff:
          description: "Staff"
          display_name: "Staff"
          route: sis_HEd_offering_sections_staff
          sort: 3
        Roster:
          description: "Roster"
          display_name: "Roster"
          route: sis_HEd_offering_sections_roster
          sort: 4
        WaitList:
          description: "Wait List"
          display_name: "Wait List"
          route: sis_HEd_offering_sections_waitlist
          sort: 5
        Grades:
          description: "Grades"
          display_name: "Grades"
          route: sis_HEd_offering_sections_grades
          sort: 6
      menu_actions:
        AddSection:
          description: "Add Section"
          display_name: "Add Section"
          route: sis_HEd_offering_sections_add
          sort: 1
        ActivateInactive:
          description: "Activate/Inactivate"
          display_name: "Activate/Inactivate"
          route: sis_HEd_offering_sections_inactivate
          divider_before: true
          record_loaded: true
          sort: 2
        DeleteSection:
          description: "Delete Section"
          display_name: "Delete Section"
          route: sis_HEd_offering_sections_delete
          record_loaded: true
          sort: 3
        RecalculateTotals:
          description: "Recalculate Totals"
          display_name: "Recalculate Totals"
          route: sis_HEd_offering_sections_recalculateSectionTotals
          divider_before: true
          sort: 4
      menu_reports:
        ClassRoster:
          description: "Class Roster"
          display_name: "Class Roster"
          route: sis_HEd_offering_sections_reports_classroster
          sort: 1
        MasterSchedule:
          description: "Master Schedule"
          display_name: "Master Schedule"
          route: sis_HEd_offering_sections_reports_masterschedule
          sort: 2
    Courses:
      description: "Courses"
      display_name: "Courses"
      sort: 2
      tabs:
        Information:
          description: "Information"
          display_name: "Information"
          route: sis_HEd_courses
          sort: 1
        Prerequisites:
          description: "Prerequisites"
          display_name: "Prerequisites"
          route: sis_HEd_courses_prerequisites
          sort: 2
        Corequisites:
          description: "Corequisites"
          display_name: "Corequisites"
          route: sis_HEd_courses_corequisites
          sort: 3
        Fees:
          description: "Fees"
          display_name: "Fees"
          route: sis_HEd_courses_fees
          sort: 4
        Books:
          description: "Books"
          display_name: "Books"
          route: sis_HEd_courses_books
          sort: 5
      menu_actions:
        NewCourse:
          description: "New Course"
          display_name: "New Course"
          route: sis_HEd_courses_add
          sort: 1
        DeleteCourse:
          description: "Delete Course"
          display_name: "Delete Course"
          divider_before: true
          record_loaded: true
          route: sis_HEd_courses_delete
          sort: 2
    Rooms:
      description: "Rooms"
      display_name: "Rooms"
      route: sis_HEd_rooms
      sort: 3

SIS.HEd.Reports.Academic:
  description: "Academic"
  display_name: "Academic (HEd)"
  type: report_group
  portal: sis
  sort: 1
  reports:
    ClassRoster:
      description: "Class Roster"
      display_name: "Class Roster"
      route: sis_HEd_offering_sections_reports_classroster
      sort: 1
    MasterSchedule:
      description: "Master Schedule"
      display_name: "Master Schedule"
      route: sis_HEd_offering_sections_reports_masterschedule
      sort: 2
      
SIS.HEd.Academic.Staff:
  description: "Staff"
  display_name: "Staff"
  type: form
  portal: sis
  tabs:
    Schedule:
      description: "Schedule"
      display_name: "Schedule"
      sort: 3
      route: sis_HEd_offering_staff_schedule
  menu_reports:
    InstructorSchedule:
      description: "Instructor Schedule"
      display_name: "Instructor Schedule"
      sort: 1
      route: sis_HEd_offering_staff_reports_schedule