Core.HEd.Scheduling:
  parent: Core.HEd
  type: dir
  display_name: "Scheduling"
  forms:
    StudentSchedule:
      description: "Student Schedule"
      display_name: "Student Schedule"
      tabs:
        CurrentSchedule:
          description: "Current Schedule"
          display_name: "Current Schedule"
          route: Core_HEd_Scheduling_StudentSchedule
        History:
          description: "History"
          display_name: "History"
          route: Core_HEd_Scheduling_StudentSchedule_History
        WaitList:
          description: "Wait List"
          display_name: "Wait List"
          route: Core_HEd_Scheduling_StudentSchedule_WaitList
      menu_actions:
        AddClasses:
          description: "Add Classes"
          display_name: "Add Classes"
          record_loaded: true
          route: Core_HEd_Scheduling_StudentSchedule_Add
        CalculateFTEAndTuition:
          description: "Calculate FTE and Tuition"
          display_name: "Calculate FTE & Tuition"
          divider_before: true
          route: Core_HEd_Scheduling_StudentSchedule_CalculateTotals
      menu_reports:
        StudentSchedule:
          description: "Student Schedule"
          display_name: "Student Schedule"
          route: Core_HEd_Scheduling_Reports_StudentSchedule
        StudentScheduleBill:
          description: "Student Schedule & Bill"
          display_name: "Student Schedule & BIll"
          route: Core_HEd_Scheduling_Reports_StudentScheduleBill
    Section:
      description: "Section"
      display_name: "Section"
      tabs:
        Basic:
          description: "Basic"
          display_name: "Basic"
          route: Core_HEd_Scheduling_Section
        Course:
          description: "Course"
          display_name: "Courses"
          route: Core_HEd_Scheduling_Section_Courses
        Staff:
          description: "Staff"
          display_name: "Staff"
          route: Core_HEd_Scheduling_Section_Staff
        Roster:
          description: "Roster"
          display_name: "Roster"
          route: Core_HEd_Scheduling_Section_Roster
        WaitList:
          description: "Wait List"
          display_name: "Wait List"
          route: Core_HEd_Scheduling_Section_WaitList
        ContactInfo:
          description: "Contact Information"
          display_name: "Contact Info"
          route: Core_HEd_Scheduling_Section_ContactInfo
      button_add:
        route: Core_HEd_Scheduling_Section_Add
      button_delete:
        route: Core_HEd_Scheduling_Section_Delete
      menu_actions:
        ActivateInactive:
          description: "Activate/Inactivate"
          display_name: "Activate/Inactivate"
          route: Core_HEd_Scheduling_Section_Inactivate
          record_loaded: true
        RecalculateTotals:
          description: "Recalculate Totals"
          display_name: "Recalculate Totals"
          route: Core_HEd_Scheduling_Section_RecalculateTotals
          divider_before: true
      menu_reports:
        ClassRoster:
          description: "Class Roster"
          display_name: "Class Roster"
          route: Core_HEd_Scheduling_Reports_ClassRoster
        ClassRosterDirectory:
          description: "Class Roster Directory"
          display_name: "Class Roster Directory"
          route: Core_HEd_Scheduling_Reports_ClassRosterDirectory
        MasterSchedule:
          description: "Master Schedule"
          display_name: "Master Schedule"
          route: Core_HEd_Scheduling_Reports_MasterSchedule

Core.HEd.Scheduling.Reports:
  type: dir
  parent: Core.HEd.Scheduling
  display_name: "Reports"
  reports:
    InstructorSchedule:
      description: "Instructor Schedule"
      display_name: "Instructor Schedule"
      route: Core_HEd_Scheduling_Reports_StaffSchedule
    StudentSchedule:
      description: "Student Schedule"
      display_name: "Student Schedule"
      route: Core_HEd_Scheduling_Reports_StudentSchedule
    StudentScheduleBill:
      description: "Student Schedule & Bill"
      display_name: "Student Schedule & Bill"
      route: Core_HEd_Scheduling_Reports_StudentScheduleBill
    ClassRoster:
      description: "Class Roster"
      display_name: "Class Roster"
      route: Core_HEd_Scheduling_Reports_ClassRoster
    ClassRosterDirectory:
      description: "Class Roster Directory"
      display_name: "Class Roster Directory"
      route: Core_HEd_Scheduling_Reports_ClassRosterDirectory
    MasterSchedule:
      description: "Master Schedule"
      display_name: "Master Schedule"
      route: Core_HEd_Scheduling_Reports_MasterSchedule

Core.HEd.Course:
  parent: Core.HEd
  description: "Course"
  display_name: "Course"
  type: dir
  forms: 
    Course:
      description: "Course"
      display_name: "Course"
      tabs:
        Information:
          description: "Information"
          display_name: "Information"
          route: Core_HEd_Course_Course
        Prerequisites:
          description: "Prerequisites"
          display_name: "Prerequisites"
          route: Core_HEd_Course_Course_Prerequisites
        Corequisites:
          description: "Corequisites"
          display_name: "Corequisites"
          route: Core_HEd_Course_Course_Corequisites
        Books:
          description: "Books"
          display_name: "Books"
          route: Core_HEd_Course_Course_Books
      button_add:
        route: Core_HEd_Course_Course_Add
      button_delete:
        route: Core_HEd_Course_Course_Delete
        
Core.HEd.Setup.Rooms:
  parent: Core.HEd.Setup
  type: form
  description: "Rooms"
  display_name: "Rooms"
  route: Core_HEd_Setup_Rooms

Core.HEd.Student.Enrollment.Registration:
  parent: Core.HEd.Student.Enrollment
  type: tab
  description: "Registration"
  display_name: "Registration"
  route: Core_HEd_Student_Enrollment_Registration
      
Core.HEd.Staff.Staff:
  tabs:
    Schedule:
      description: "Schedule"
      display_name: "Schedule"
      route: Core_HEd_Staff_Staff_Schedule
  menu_reports:
    InstructorSchedule:
      description: "Instructor Schedule"
      display_name: "Instructor Schedule"
      route: Core_HEd_Scheduling_Reports_StaffSchedule

Core.Constituent.Combiner.CourseHEd:
  parent: Core.Constituent.Combiner
  type: tab
  target: HEd
  description: "Course Combiner"
  display_name: "Course"
  route: Core_Constituent_Combiner_Course_HEd

Core.HEd.Setup.School.Registration:
  parent: Core.HEd.Setup.School
  type: tab
  description: "Registration"
  display_name: "Registration"
  route: Core_HEd_Setup_School_Registration_GradeLevels

Teacher.HEd.Roster:
  description: "Roster"
  display_name: "Roster"
  parent: Teacher.HEd
  type: form
  tabs:
    Current:
      description: "Current Roster"
      display_name: "Current"
      route: Teacher_HEd_Roster
    Dropped:
      description: "Dropped Roster"
      display_name: "Dropped"
      route: Teacher_HEd_Roster_Dropped
  menu_reports:
    ClassRoster:
      description: "Class Roster"
      display_name: "Class Roster"
      route: Teacher_HEd_Reports_ClassRoster
      
Teacher.HEd.Advisee:
  description: "Advisee"
  display_name: "Advisee"
  parent: Teacher.HEd
  type: form
  tabs:
    Schedule:
      description: "Schedule"
      display_name: "Schedule"
      route: Teacher_HEd_Student_Schedule

Student.HEd.Schedule:
  type: form
  parent: Student.HEd
  description: "Schedule"
  display_name: "Schedule"
  route: Student_HEd_Schedule

Student.HEd.Registration:
  type: form
  parent: Student.HEd
  description: "Registration"
  display_name: "Registration"
  route: Student_HEd_Registration

Core.HEd.Course.Course.Fees:
  description: "Fees"
  display_name: "Fees"
  type: tab
  parent: Core.HEd.Course.Course
  route: Core_HEd_Course_Course_Fees

Core.HEd.Scheduling.Section.Fees:
  description: "Fees"
  display_name: "Fees"
  type: tab
  parent: Core.HEd.Scheduling.Section
  route: Core_HEd_Scheduling_Section_Fees