Core.HEd.Course:
  class: Kula\HEd\Bundle\SchedulingBundle\Record\CoreCourseRecord
Core.HEd.Section:
  class: Kula\HEd\Bundle\SchedulingBundle\Record\CoreSectionRecord
Teacher.HEd.Section:
  class: Kula\HEd\Bundle\SchedulingBundle\Record\TeacherSectionRecord