_HEd_scheduling_core:
    resource: "@KulaHEdSchedulingBundle/Resources/config/routing/core.yml"
    prefix: core/HEd

_HEd_scheduling_teacher:
    resource: "@KulaHEdSchedulingBundle/Resources/config/routing/teacher.yml"
    prefix: teacher/HEd

_HEd_scheduling_student:
    resource: "@KulaHEdSchedulingBundle/Resources/config/routing/student.yml"
    prefix: student/HEd

_HEd_scheduling_api:
    resource: "@KulaHEdSchedulingBundle/Resources/config/routing/api.yml"
    prefix: api/HEd
