Core_K12_Staff_Staff_Schedule:
  path: /staff/staff/schedule
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreStaff:staff_schedule
    _navigation: Core.K12.Staff.Staff.Schedule

Core_K12_Scheduling_StudentSchedule:
  path: /scheduling/student_schedule
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreSchedule:index
    _navigation: Core.K12.Scheduling.StudentSchedule.CurrentSchedule

Core_K12_Scheduling_StudentSchedule_Add:
  path: /scheduling/student_schedule/add
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreSchedule:add
    _navigation: Core.K12.Scheduling.StudentSchedule

Core_K12_Scheduling_StudentSchedule_CalculateTotals:
  path: /scheduling/student_schedule/calculate_totals
  defaults: { _controller: KulaK12SchedulingBundle:CoreSchedule:calculateTotals }

Core_K12_Scheduling_StudentSchedule_Detail:
  path: /scheduling/student_schedule/detail/{id}
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreSchedule:detail
    _navigation: Core.K12.Scheduling.StudentSchedule

Core_K12_Scheduling_StudentSchedule_History:
  path: /scheduling/student_schedule/history
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreSchedule:history
    _navigation: Core.K12.Scheduling.StudentSchedule.History

Core_K12_Scheduling_Reports_StudentSchedule:
  path: /scheduling/reports/student_schedule
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreStudentScheduleReport:index
    _navigation: Core.K12.Scheduling.Reports.StudentSchedule
  methods: [GET]

Core_K12_Scheduling_Reports_StudentSchedule_Generate:
  path: /scheduling/reports/student_schedule
  defaults: { _controller: KulaK12SchedulingBundle:CoreStudentScheduleReport:generate }
  methods: [POST]

Core_K12_Scheduling_Reports_StudentScheduleBill:
  path: /scheduling/reports/student_schedule_bill
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreStudentScheduleBillReport:index
    _navigation: Core.K12.Scheduling.Reports.StudentScheduleBill
  methods: [GET]
  
Core_K12_Scheduling_Reports_StudentScheduleBill_Generate:
  path: /scheduling/reports/student_schedule_bill
  defaults: { _controller: KulaK12SchedulingBundle:CoreStudentScheduleBillReport:generate }
  methods: [POST]

Core_K12_Scheduling_StudentSchedule_WaitList:
  path: /scheduling/student_schedule/wait_list
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreSchedule:waitlist
    _navigation: Core.K12.Scheduling.StudentSchedule.WaitList

Core_K12_Scheduling_Section:
  path: /scheduling/section
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreSection:index
    _navigation: Core.K12.Scheduling.Section.Basic

Core_K12_Scheduling_Section_Add:
  path: /scheduling/section/add
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreSection:add
    _navigation: Core.K12.Scheduling.Section
  methods: [GET]

Core_K12_Scheduling_Section_Create:
  path: /scheduling/section/add
  defaults: { _controller: KulaK12SchedulingBundle:CoreSection:create }
  methods: [POST]

Core_K12_Scheduling_Section_Delete:
  path: /scheduling/section/delete
  defaults: { _controller: KulaK12SchedulingBundle:CoreSection:delete }
  methods: [POST]

Core_K12_Scheduling_Section_Inactivate:
  path: /scheduling/section/inactivate
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreSection:inactivate
    _navigation: Core.K12.Scheduling.Section.ActivateInactive
  methods: [POST]

Core_K12_Scheduling_Reports_ClassRoster_Generate:
  path: /scheduling/reports/class_roster
  defaults: { _controller: KulaK12SchedulingBundle:CoreClassRosterReport:generate }
  methods: [POST]

Core_K12_Scheduling_Reports_ClassRoster:
  path: /scheduling/reports/class_roster
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreClassRosterReport:index
    _navigation: Core.K12.Scheduling.Reports.ClassRoster
  methods: [GET]
  
Core_K12_Scheduling_Reports_ClassRosterDirectory:
  path: /scheduling/reports/class_roster_directory
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreClassRosterDirectoryReport:index
    _navigation: Core.K12.Scheduling.Reports.ClassRosterDirectory
  methods: [GET]

Core_K12_Scheduling_Reports_ClassRosterDirectory_Generate:
  path: /scheduling/reports/class_roster_directory/generate
  defaults: { _controller: KulaK12SchedulingBundle:CoreClassRosterDirectoryReport:generate }
  methods: [POST]
  
Core_K12_Scheduling_Reports_MasterSchedule:
  path: /scheduling/reports/master_schedule
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreMasterScheduleReport:index
    _navigation: Core.K12.Scheduling.Reports.MasterSchedule
  methods: [GET]

Core_K12_Scheduling_Reports_MasterSchedule_Generate:
  path: /scheduling/reports/master_schedule
  defaults: { _controller: KulaK12SchedulingBundle:CoreMasterScheduleReport:generate }
  methods: [POST]

Core_K12_Scheduling_Section_Roster:
  path: /scheduling/section/roster
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreSection:roster
    _navigation: Core.K12.Scheduling.Section.Roster

Core_K12_Scheduling_Section_WaitList:
  path: /scheduling/section/waitlist
  defaults:
    _controller: KulaK12SchedulingBundle:CoreSection:waitlist
    _navigation: Core.K12.Scheduling.Section.WaitList

Core_K12_Scheduling_Reports_StaffSchedule:
  path: /scheduling/reports/instructor_schedule
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreStaffScheduleReport:index
    _navigation: Core.K12.Scheduling.Reports.InstructorSchedule
  methods: [GET]

Core_K12_Scheduling_Reports_StaffSchedule_Generate:
  path: /scheduling/reports/instructor_schedule
  defaults: { _controller: KulaK12SchedulingBundle:CoreStaffScheduleReport:generate }
  methods: [POST]

Core_K12_Scheduling_Section_RecalculateTotals:
  path: /scheduling/section/recalculate_totals
  defaults: { _controller: KulaK12SchedulingBundle:CoreSection:recalculate_section_totals }

Core_K12_Scheduling_Section_Courses:
  path: /scheduling/sections/courses
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreSection:courses
    _navigation: Core.K12.Scheduling.Section.Course

Core_K12_Scheduling_Section_Staff:
  path: /scheduling/section/staff
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreSection:staff
    _navigation: Core.K12.Scheduling.Section.Staff

Core_K12_Course_Chooser:
  path: /course/chooser
  defaults: { _controller: KulaK12SchedulingBundle:CoreCourses:chooser }

Core_K12_Course_Course:
  path: /course/course
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreCourses:index
    _navigation: Core.K12.Course.Course.Information

Core_K12_Course_Course_Add:
  path: /course/course/add
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreCourses:add
    _navigation: Core.K12.Course.Course
  methods: [GET]

Core_Constituent_Combiner_Course_K12: 
    path:     /constituent/combiner/course
    defaults: 
      _controller: KulaK12SchedulingBundle:CoreCourses:combine
      _navigation: Core.Constituent.Combiner.Course

Core_K12_Course_Course_Books:
  path: /course/course/books
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreBooks:books
    _navigation: Core.K12.Course.Course.Books

Core_K12_Course_Course_Corequisites:
  path: /course/course/corequisites
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreCourses:corequisites
    _navigation: Core.K12.Course.Course.Corequisites

Core_K12_Course_Course_Create:
  path: /course/course/add
  defaults: { _controller: KulaK12SchedulingBundle:CoreCourses:create }
  methods: [POST]

Core_K12_Course_Course_Delete:
  path: /course/course/delete
  defaults: { _controller: KulaK12SchedulingBundle:CoreCourses:delete }
  methods: [POST]

Core_K12_Course_Course_Prerequisites:
  path: /course/course/prerequisites
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreCourses:prerequisites
    _navigation: Core.K12.Course.Course.Prerequisites

Core_K12_Setup_Rooms_Chooser:
  path: /setup/rooms/chooser
  defaults: { _controller: KulaK12SchedulingBundle:CoreRooms:chooser }
  methods: [GET]

Core_K12_Setup_Rooms:
  path: /setup/rooms
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreRooms:index
    _navigation: Core.K12.Setup.Room
    
Core_K12_Scheduling_Reports_ClassRosterSignInOut:
    path: /scheduling/reports/class_roster_sign_in_out
    defaults: 
      _controller: KulaK12SchedulingBundle:CoreClassRosterSignInOutReport:index
      _navigation: Core.K12.Scheduling.Reports.ClassRosterSignInOut
    methods: [GET]

Core_K12_Scheduling_Report_ClassRosterSignInOut_Generate:
  path: /scheduling/reports/class_roster_sign_in_out
  defaults: { _controller: KulaK12SchedulingBundle:CoreClassRosterSignInOutReport:generate }
  methods: [POST]
  
Core_K12_Scheduling_Reports_ClassRoster_AA:
  path: /scheduling/reports/class_roster/aa
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreAAClassRosterReport:index
    _navgiation: Core.K12.Scheduling.Reports.AAClassRoster
  methods: [GET]

Core_K12_Scheduling_Reports_ClassRoster_AA_Generate:
  path: /scheduling/reports/class_roster/aa
  defaults: { _controller: KulaK12SchedulingBundle:CoreAAClassRosterReport:generate }
  methods: [POST]
  
Core_K12_Scheduling_Reports_ClassRoster_Labels_AA:
  path: /scheduling/reports/class_roster_labels/aa
  defaults: 
    _controller: KulaK12SchedulingBundle:CoreAAClassRosterLabelsReport:index
    _navigation: Core.K12.Scheduling.Reports.AAClassRosterLabels
  methods: [GET]

Core_K12_Scheduling_Reports_ClassRoster_Labels_AA_Generate:
  path: /scheduling/reports/class_roster_labels/aa
  defaults: { _controller: KulaK12SchedulingBundle:CoreAAClassRosterLabelsReport:generate }
  methods: [POST]