teacher_K12_class_roster:
  path: /class/roster
  defaults: { _controller: KulaK12SchedulingBundle:TeacherSection:roster }

teacher_K12_class_roster_dropped:
  path: /class/roster/dropped
  defaults: { _controller: KulaK12SchedulingBundle:TeacherSection:dropped_roster }

teacher_K12_offering_sections_report_classroster_generate:
  path: /offering/section/reports/roster/generate
  defaults: { _controller: KulaK12SchedulingBundle:TeacherClassRosterReport:generate }
  methods: [POST]

teacher_K12_offering_sections_reports_classroster:
  path: /offering/sections/reports/classroster
  defaults: { _controller: KulaK12SchedulingBundle:TeacherClassRosterReport:index }
