pages:
  Core.Pages.Home:
    description: "Home Page"
    display_name: "Home"
form_groups:
  Core.FormGroups.System:
    description: "System"
    display_name: "System"
    sort: 1
forms:
  Core.Forms.System.Lookup:
    parent: Core.FormGroups.System
    description: "Lookup"
    display_name: "Lookup"
    sort: 1