Core.System.Monitor:
  type: dir
  parent: Core.System
  description: "Forms that display activity in system."
  display_name: "Monitor"
  
Core.System.Monitor.Logs:
  type: form
  parent: Core.System.Monitor
  description: "Logs"
  display_name: "Logs"
  route: Core_Logs_Session

Core.System.Monitor.APILogs:
  type: form
  parent: Core.System.Monitor
  description: "API Logs"
  display_name: "API Logs"
  tabs:
    Sessions:
      description: "Sessions"
      display_name: "Sessions"
      route: Core_Logs_API_Session
    ErrorRequests:
      description: "Error Requests"
      display_name: "Error Requests"
      route: Core_Logs_API_Session_Requests_Error

Core.System.Setup:
  type: form
  parent: Core.System
  description: "Setup"
  display_name: "Setup"
  tabs:
    General:
      description: "General"
      display_name: "General"
      route: Core_Setup_System
    LDAP:
      description: "LDAP"
      display_name: "LDAP"
      route: Core_Setup_System_LDAP
    IntegrationDatabases:
      description: "Integration Databases"
      display_name: "Integration DBs"
      route: Core_System_Integration_Databases
    IntegrationAPIApps:
      description: "Integration API Applications"
      display_name: "API Applications"
      route: Core_System_Integration_API_Apps
    
Core.System.Lookup:
  type: form
  parent: Core.System
  description: "Lookup"
  display_name: "Lookup"
  route: Core_System_Lookup
  button_add:
    route: Core_System_Lookup_Add
  button_delete:
    route: Core_System_Lookup_Delete
    confirmation_message: "Are you sure you want to delete lookup?"

Core.System.NonOrganization:
  type: form
  parent: Core.System
  description: "Non Organization"
  display_name: "Non Organization"
  route: Core_System_NonOrganization
  button_add: 
    route: Core_System_NonOrganization_Add
  button_delete:
    route: Core_System_NonOrganization_Delete
    confirmation_message: "Are you sure you want to delete non organization?"

Core.System.Organization:
  type: form
  parent: Core.System
  description: "Organization"
  display_name: "Organization"
  tabs:
    OrganizationTerms:
      description: "Organization Terms"
      display_name: "Organization Terms"
      route: Core_System_Organization_Terms
    Organization:
      description: "Organization"
      display_name: "Organization"
      route: Core_System_Organization

Core.System.Terms:
  type: form
  parent: Core.System
  description: "Terms"
  display_name: "Terms"
  route: Core_System_Terms

Core.System.NavigationPermissions:
  type: form
  parent: Core.System
  description: "Navigation Permissions"
  display_name: "Navigation Permissions"
  tabs:
    UserGroup:
      description: "User Group"
      display_name: "User Group"
      route: Core_System_NavPermissions_Usergroup	
    Public:
      description: "Public"
      display_name: "Public"
      route: Core_System_NavPermissions_Public
    Role:
      description: "Role"
      display_name: "Role"
      route: Core_System_NavPermissions_Role

Core.System.SchemaPermissions:
  type: form
  parent: Core.System
  description: "Schema Permissions"
  display_name: "Schema Permissions"
  tabs:
    UserGroup:
      description: "User Group"
      display_name: "User Group"
      route: Core_System_SchemaPermissions_Usergroup
    Public:
      description: "Public"
      display_name: "Public"
      route: Core_System_SchemaPermissions_Public
    Role:
      description: "Role"
      display_name: "Role"
      route: Core_System_SchemaPermissions_Role

Core.System.UserGroups:
  type: form
  parent: Core.System
  description: "User Groups"
  display_name: "User Groups"
  route: Core_System_Usergroups
  
Core.System.Users:
  type: form
  parent: Core.System
  description: "Users"
  display_name: "Users"
  tabs:
    Information:
      description: "User Information"
      display_name: "Information"
      route: Core_System_Users
    UserGroups:
      description: "Roles"
      display_name: "Roles"
      route: Core_System_Users_Usergroups
  button_add:
    route: Core_System_Users_Add
  button_delete:
    route: Core_System_Users_Delete
    confirmation_message: "Are you sure you want to delete user?"