Core.FormGroups.System:
  description: "System"
  display_name: "System"
  type: form_group
  portal: core
  sort: 1
  

Core.Forms.System.Lookup:
  parent: Core.FormGroups.System
  description: "Lookup"
  display_name: "Lookup"
  type: form
  portal: core
  route: core_system_lookup
  sort: 1
Core.MenuActions.System.Lookup.New:
  parent: Core.Forms.System.Lookup
  description: "New Lookup"
  display_name: "New Lookup"
  type: menu_action
  portal: core
  route: core_system_lookup_add
  sort: 1
Core.MenuActions.System.Lookup.Delete:
  parent: Core.Forms.System.Lookup
  description: "Delete Lookup"
  display_name: "Delete Lookup"
  type: menu_action
  divider_before: true
  record_loaded: true
  portal: core
  route: core_system_lookup_delete
  confirmation_message: "Are you sure you want to delete lookup?"
  sort: 2

Core.FormGroups.User:
  description: "User"
  display_name: "User"
  type: form_group
  portal: core
  sort: 1
Core.Forms.User.UserGroup:
  parent: Core.FormGroups.User
  description: "User Groups"
  display_name: "User Groups"
  type: form
  portal: core
  route: core_system_users
  sort: 1