Core.NavigationForm:
  class: Kula\Core\Bundle\SystemBundle\Record\NavigationFormRecord
Core.SchemaTable:
  class: Kula\Core\Bundle\SystemBundle\Record\SchemaTableRecord
Core.Lookup:
  class: Kula\Core\Bundle\SystemBundle\Record\LookupRecord
