Core.Lookup:
  class: Kula\Core\Bundle\SystemBundle\Record\LookupRecord
Core.Usergroup:
  class: Kula\Core\Bundle\SystemBundle\Record\UserGroupRecord
Core.User.Role:
  class: Kula\Core\Bundle\SystemBundle\Record\RoleRecord
Core.User:
  class: Kula\Core\Bundle\SystemBundle\Record\UserRecord
Core.Organization.School:
  class: Kula\Core\Bundle\SystemBundle\Record\SchoolRecord
Core.Organization.School.Term:
  class: Kula\Core\Bundle\SystemBundle\Record\SchoolTermRecord
Core.NonOrganization:
  class: Kula\Core\Bundle\SystemBundle\Record\NonOrganizationRecord
  
SIS.Lookup:
  class: Kula\Core\Bundle\SystemBundle\Record\LookupRecord
SIS.Organization.School:
  class: Kula\Core\Bundle\SystemBundle\Record\SchoolRecord
SIS.Organization.School.Term:
  class: Kula\Core\Bundle\SystemBundle\Record\SchoolTermRecord
SIS.NonOrganization:
  class: Kula\Core\Bundle\SystemBundle\Record\NonOrganizationRecord