parameters:
  kula.core.poster_factory.class: Kula\Core\Component\DB\PosterFactory

services:
  kula.core.user:
    class: Kula\Core\Bundle\SystemBundle\Service\UserService
    arguments: ["@kula.core.db", "@kula.core.poster_factory"]
  kula.job:
    class: Kula\Core\Bundle\SystemBundle\Service\JobQueueService
    arguments: ["@kula.core.db", "@kula.core.session", "@kula.core.focus", "@kula.core.navigation"]