Core.Home:
  description: "Home"
  display_name: "Home"
  type: form
  route: Core_Home
  first: core
  portal: core

Teacher.Home:
  description: "Home"
  display_name: "Home"
  type: form
  route: Teacher_Home
  first: teacher
  portal: teacher
  
Student.Home:
  description: "Home"
  display_name: "Home"
  type: form
  route: Student_Home
  first: student
  portal: student