Core_Home:
    path:     /core/home
    defaults: 
      _controller: KulaCoreHomeBundle:CoreHome:home
      _navigation: Core.Home

Teacher_Home:
    path:     /teacher/home
    defaults: 
      _controller: KulaCoreHomeBundle:TeacherHome:home
      _navigation: Teacher.Home

Student_Home:
    path:     /student/home
    defaults: 
      _controller: KulaCoreHomeBundle:Home:home
      _navigation: Student.Home