core_home:
    path:     /core/home
    defaults: { _controller: KulaCoreHomeBundle:Home:home }

sis_home:
    path:     /sis/home
    defaults: { _controller: KulaCoreHomeBundle:SISHome:home }

teacher_home:
    path:     /teacher/home
    defaults: { _controller: KulaCoreHomeBundle:TeacherHome:home }