Core.K12.Scheduling:
  parent: Core.K12
  type: dir
  display_name: "Scheduling"
  forms:
    StudentSchedule:
      description: "Student Schedule"
      display_name: "Student Schedule"
      tabs:
        CurrentSchedule:
          description: "Current Schedule"
          display_name: "Current Schedule"
          route: Core_K12_Scheduling_StudentSchedule
        History:
          description: "History"
          display_name: "History"
          route: Core_K12_Scheduling_StudentSchedule_History
        WaitList:
          description: "Wait List"
          display_name: "Wait List"
          route: Core_K12_Scheduling_StudentSchedule_WaitList
      menu_actions:
        AddClasses:
          description: "Add Classes"
          display_name: "Add Classes"
          record_loaded: true
          route: Core_K12_Scheduling_StudentSchedule_Add
        CalculateFTEAndTuition:
          description: "Calculate FTE and Tuition"
          display_name: "Calculate FTE & Tuition"
          divider_before: true
          record_loaded: true
          route: Core_K12_Scheduling_StudentSchedule_CalculateTotals
      menu_reports:
        StudentSchedule:
          description: "Student Schedule"
          display_name: "Student Schedule"
          route: Core_K12_Scheduling_Reports_StudentSchedule
        StudentScheduleBill:
          description: "Student Schedule & Bill"
          display_name: "Student Schedule & BIll"
          route: Core_K12_Scheduling_Reports_StudentScheduleBill
    Section:
      description: "Section"
      display_name: "Section"
      tabs:
        Basic:
          description: "Basic"
          display_name: "Basic"
          route: Core_K12_Scheduling_Section
        Course:
          description: "Course"
          display_name: "Courses"
          route: Core_K12_Scheduling_Section_Courses
        Staff:
          description: "Staff"
          display_name: "Staff"
          route: Core_K12_Scheduling_Section_Staff
        Roster:
          description: "Roster"
          display_name: "Roster"
          route: Core_K12_Scheduling_Section_Roster
        WaitList:
          description: "Wait List"
          display_name: "Wait List"
          route: Core_K12_Scheduling_Section_WaitList
      button_add:
        route: Core_K12_Scheduling_Section_Add
      button_delete:
        route: Core_K12_Scheduling_Section_Delete
      menu_actions:
        ActivateInactive:
          description: "Activate/Inactivate"
          display_name: "Activate/Inactivate"
          route: Core_K12_Scheduling_Section_Inactivate
          record_loaded: true
        RecalculateTotals:
          description: "Recalculate Totals"
          display_name: "Recalculate Totals"
          route: Core_K12_Scheduling_Section_RecalculateTotals
          divider_before: true
      menu_reports:
        ClassRoster:
          description: "Class Roster"
          display_name: "Class Roster"
          route: Core_K12_Scheduling_Reports_ClassRoster
        ClassRosterDirectory:
          description: "Class Roster Directory"
          display_name: "Class Roster Directory"
          route: Core_K12_Scheduling_Reports_ClassRosterDirectory
        MasterSchedule:
          description: "Master Schedule"
          display_name: "Master Schedule"
          route: Core_K12_Scheduling_Reports_MasterSchedule

Core.K12.Scheduling.Reports:
  type: dir
  parent: Core.K12.Scheduling
  display_name: "Reports"
  reports:
    InstructorSchedule:
      description: "Instructor Schedule"
      display_name: "Instructor Schedule"
      route: Core_K12_Scheduling_Reports_StaffSchedule
    StudentSchedule:
      description: "Student Schedule"
      display_name: "Student Schedule"
      route: Core_K12_Scheduling_Reports_StudentSchedule
    StudentScheduleBill:
      description: "Student Schedule & Bill"
      display_name: "Student Schedule & Bill"
      route: Core_K12_Scheduling_Reports_StudentScheduleBill
    ClassRoster:
      description: "Class Roster"
      display_name: "Class Roster"
      route: Core_K12_Scheduling_Reports_ClassRoster
    ClassRosterDirectory:
      description: "Class Roster Directory"
      display_name: "Class Roster Directory"
      route: Core_K12_Scheduling_Reports_ClassRosterDirectory
    MasterSchedule:
      description: "Master Schedule"
      display_name: "Master Schedule"
      route: Core_K12_Scheduling_Reports_MasterSchedule
    ClassRosterSignInOut:
      description: "Class Roster Sign In Out"
      display_name: "Class Roster Sign In Out"
      route: Core_K12_Scheduling_Reports_ClassRosterSignInOut
    AAClassRoster:
      description: "AA Class Roster"
      display_name: "AA Class Roster"
      route: Core_K12_Scheduling_Reports_ClassRoster_AA
    AAClassRosterLabels:
      description: "AA Class Roster Labels"
      display_name: "AA Class Roster Labels"
      route: Core_K12_Scheduling_Reports_ClassRoster_Labels_AA

Core.K12.Course:
  parent: Core.K12
  description: "Course"
  display_name: "Course"
  type: dir
  forms: 
    Course:
      description: "Course"
      display_name: "Course"
      tabs:
        Information:
          description: "Information"
          display_name: "Information"
          route: Core_K12_Course_Course
        Prerequisites:
          description: "Prerequisites"
          display_name: "Prerequisites"
          route: Core_K12_Course_Course_Prerequisites
        Corequisites:
          description: "Corequisites"
          display_name: "Corequisites"
          route: Core_K12_Course_Course_Corequisites
        Books:
          description: "Books"
          display_name: "Books"
          route: Core_K12_Course_Course_Books
      button_add:
        route: Core_K12_Course_Course_Add
      button_delete:
        route: Core_K12_Course_Course_Delete
        
Core.K12.Setup.Rooms:
  parent: Core.K12.Setup
  type: form
  description: "Rooms"
  display_name: "Rooms"
  route: Core_K12_Setup_Rooms
      
Core.K12.Staff.Staff:
  tabs:
    Schedule:
      description: "Schedule"
      display_name: "Schedule"
      route: Core_K12_Staff_Staff_Schedule
  menu_reports:
    InstructorSchedule:
      description: "Instructor Schedule"
      display_name: "Instructor Schedule"
      route: Core_K12_Scheduling_Reports_StaffSchedule

Core.Constituent.Combiner.CourseK12:
  parent: Core.Constituent.Combiner
  type: tab
  target: K12
  description: "Course Combiner"
  display_name: "Course"
  route: Core_Constituent_Combiner_Course_K12