Core.K12.Course:
  class: Kula\K12\Bundle\SchedulingBundle\Record\CoreCourseRecord
Core.K12.Section:
  class: Kula\K12\Bundle\SchedulingBundle\Record\CoreSectionRecord
Teacher.K12.Section:
  class: Kula\K12\Bundle\SchedulingBundle\Record\TeacherSectionRecord