SIS.HEd.Course:
  class: Kula\HEd\Bundle\SchedulingBundle\Record\SISCourseRecord
SIS.HEd.Section:
  class: Kula\HEd\Bundle\SchedulingBundle\Record\SISSectionRecord
Teacher.HEd.Section:
  class: Kula\HEd\Bundle\SchedulingBundle\Record\TeacherSectionRecord