SIS.K12.Course:
  class: Kula\K12\Bundle\SchedulingBundle\Record\SISCourseRecord
SIS.K12.Section:
  class: Kula\K12\Bundle\SchedulingBundle\Record\SISSectionRecord
Teacher.K12.Section:
  class: Kula\K12\Bundle\SchedulingBundle\Record\TeacherSectionRecord