_K12_scheduling_sis:
    resource: "@KulaK12SchedulingBundle/Resources/config/routing/sis.yml"
    prefix: sis/K12

_K12_scheduling_teacher:
    resource: "@KulaK12SchedulingBundle/Resources/config/routing/teacher.yml"
    prefix: teacher/K12