Core_K12_Billing_StudentBilling_Balances:
  path: /core/K12/billing/student/balances
  defaults: 
    _controller: KulaK12BillingBundle:CoreBilling:balances
    _navigation: Core.K12.Billing.StudentBilling.Balances

Core_K12_Billing_StudentBilling_AddCharge:
  path: /core/K12/billing/student/charges/add
  defaults: 
    _controller: KulaK12BillingBundle:CoreTransactions:add_charge
    _navigation: Core.K12.Billing.StudentBilling

Core_K12_Billing_StudentBilling_History:
  path: /core/K12/billing/student/history
  defaults: 
    _controller: KulaK12BillingBundle:CoreTransactions:history
    _navigation: Core.K12.Billing.StudentBilling.History

Core_K12_Billing_StudentBilling_AddPayment:
  path: /core/K12/billing/student/payments/add
  defaults: 
    _controller: KulaK12BillingBundle:CoreTransactions:add_payment
    _navigation: Core.K12.Billing.StudentBilling

Core_K12_Billing_Reports_BillingLedger:
  path: /core/K12/billing/reports/billing_ledger
  defaults: 
    _controller: KulaK12BillingBundle:CoreBillingConstituentLedgerReport:index
    _navigation: Core.K12.Billing.Reports.BillingLedger
  methods: [GET]

Core_K12_Billing_Reports_BillingLedger_Generate:
  path: /core/K12/billing/reports/billing_ledger
  defaults: { _controller: KulaK12BillingBundle:CoreBillingConstituentLedgerReport:generate }
  methods: [POST]

Core_K12_Billing_Reports_BillingReceipt:
  path: /core/K12/billing/reports/billing_receipt
  defaults: 
    _controller: KulaK12BillingBundle:CoreBillingReceiptReport:index
    _navigation: Core.K12.Billing.Reports.BillingReceipt
  methods: [GET]

Core_K12_Billing_Reports_BillingReceipt_Generate:
  path: /core/K12/billing/reports/billing_receipt
  defaults: { _controller: KulaK12BillingBundle:CoreBillingReceiptReport:generate }
  methods: [POST]

Core_K12_Billing_Reports_BillingStatement:
  path: /core/K12/billing/reports/billing_statement
  defaults: 
    _controller: KulaK12BillingBundle:CoreBillingStatementReport:index
    _navigation: Core.K12.Billing.Reports.BillingStatement
  methods: [GET]

Core_K12_Billing_Reports_BillingStatement_Generate:
  path: /core/K12/billing/reports/billing_statement
  defaults: { _controller: KulaK12BillingBundle:CoreBillingStatementReport:generate }
  methods: [POST]

Core_K12_Billing_StudentBilling_TransactionDetail:
  path: /core/K12/billing/student/transactions/{constituent_transaction_id}/detail
  defaults: { _controller: KulaK12BillingBundle:CoreTransactions:transaction_detail }

Core_K12_Billing_StudentBilling_Transactions:
  path: /core/K12/billing/student/transactions
  defaults: 
    _controller: KulaK12BillingBundle:CoreTransactions:transactions
    _navigation: Core.K12.Billing.StudentBilling.Transactions

Core_K12_Billing_Billing_Pending:
    path:     /core/K12/billing/billing/pending
    defaults: 
      _controller: KulaK12BillingBundle:CoreHomeBilling:pending
      _navigation: Core.K12.Billing.Billing.Pending

Core_K12_Billing_Billing_AllPending:
    path:     /core/K12/billing/billing/pending/all
    defaults: 
      _controller: KulaK12BillingBundle:CoreHomeBilling:all_pending
      _navigation: Core.K12.Billing.Billing.AllPending

Core_K12_Billing_Reports_StudentStatement:
  path: /core/K12/billing/reports/student_statement
  defaults: 
    _controller: KulaK12BillingBundle:CoreStudentStatementReport:index
    _navigation: Core.K12.Billing.Reports.StudentStatement
  methods: [GET]

Core_K12_Billing_BillingSetup_Codes:
  path: /core/K12/billing/setup/codes
  defaults: 
    _controller: KulaK12BillingBundle:CoreCodes:codes
    _navigation: Core.K12.Billing.BillingSetup.Codes

Core_K12_Billing_BillingSetup_TuitionRates:
  path: /core/K12/billing/setup/tuition_rates
  defaults: 
    _controller: KulaK12BillingBundle:CoreTuitionRates:index
    _navigation: Core.K12.Billing.BillingSetup.TuitionRates

Core_K12_Billing_BillingSetup_TuitionRates_Transactions:
  path: /core/K12/billing/setup/tuition_rates/{tuition_rate_id}/transactions
  defaults: 
    _controller: KulaK12BillingBundle:CoreTuitionRates:transactions
    _navigation: Core.K12.Billing.BillingSetup.TuitionRates.Transactions

Core_K12_Billing_BillingSetup_TuitionRates_Students:
  path: /core/K12/billing/setup/tuition_rates/{tuition_rate_id}/students
  defaults: 
    _controller: KulaK12BillingBundle:CoreTuitionRates:students
    _navigation: Core.K12.Billing.BillingSetup.TuitionRates.Students

Core_K12_Billing_BillingSetup_TuitionRates_Refunds:
  path: /core/K12/billing/setup/tuition_rates/{tuition_rate_id}/refunds
  defaults: 
    _controller: KulaK12BillingBundle:CoreTuitionRates:refunds
    _navigation: Core.K12.Billing.BillingSetup.TuitionRates.Refunds

Core_K12_Course_Course_Fees:
  path: /core/K12/course/course/fees
  defaults: 
    _controller: KulaK12BillingBundle:CoreCourseFees:index
    _navigation: Core.K12.Course.Course.Fees

Core_K12_Scheduling_Section_Fees:
  path: /core/K12/scheduling/sections/fees
  defaults: 
    _controller: KulaK12BillingBundle:CoreCourseFees:sectionFees
    _navigation: Core.K12.Scheduling.Section.Fees