api_v1_applicationAuthentication:
    path:     /application/authenticate
    defaults: { _controller: KulaCoreLoginBundle:APIv1Login:authenticateApplication }
    methods: [POST]

api_v1_userAuthentication:
    path:     /user/authenticate
    defaults: { _controller: KulaCoreLoginBundle:APIv1Login:authenticateUser }
    methods: [POST]

api_v1_userAuthenticatedTest:
    path:     /user/authenticate/test
    defaults: { _controller: KulaCoreLoginBundle:APIv1Login:testAuthenticatedUser }
    methods: [GET]