Core.HEd.Scheduling.StudentSchedule:
  tabs:
    Grades:
      description: "Grades"
      display_name: "Grades"
      route: Core_HEd_Scheduling_StudentSchedule_Grades
  menu_reports:
    FinalGrades:
      descriptions: "Final Grades"
      display_name: "Final Grades"
      route: Core_HEd_Grading_Reports_FinalGrades

Core.HEd.Grading:
  parent: Core.HEd
  type: dir
  description: "Grading"
  display_name: "Grading"
  forms:
    StudentCourseHistory:
      description: "Student Course History"
      display_name: "Student Course History"
      tabs:
        CourseHistory:
          description: "Course History"
          display_name: "Course History"
          route: Core_HEd_Grading_StudentCourseHistory_CourseHistory
        Degrees:
          description: "Degrees"
          display_name: "Degrees"
          route: Core_HEd_Grading_StudentCourseHistory_Degrees
        Standings:
          description: "Standings"
          display_name: "Standings"
          route: Core_HEd_Grading_StudentCourseHistory_Standings
        TranscriptComments:
          description: "Transcript Comments"
          display_name: "Transcript Comments"
          route: Core_HEd_Grading_StudentCourseHistory_TranscriptComments
        Terms:
          description: "Terms"
          display_name: "Terms"
          route: Core_HEd_Grading_StudentCourseHistory_Terms
        Transcript:
          description: "Transcript"
          display_name: "Transcript"
          route: Core_HEd_Grading_StudentCourseHistory_Transcript
        DegreeAudit:
          description: "Degree Audit"
          display_name: "Degree Audit"
          route: Core_HEd_Grading_StudentCourseHistory_DegreeAudit
      menu_actions:
        RecalculateTermTotals:
          description: "Calculate Term Totals"
          display_name: "Calculate Term Totals"
          route: Core_HEd_Grading_StudentCourseHistory_CalculateTermTotals
      menu_reports:
        StudentTranscript:
          description: "Student Transcript"
          display_name: "Student Transcript"
          route: Core_HEd_Grading_Reports_StudentTranscript
        DegreeAuditReport:
          description: "Degree Audit"
          display_name: "Degree Audit"
          route: Core_HEd_Grading_Reports_DegreeAudit
    Degrees:
      description: "Degrees"
      display_name: "Degrees"
      tabs:
        Degrees:
          description: "Degrees"
          display_name: "Degrees"
          route: Core_HEd_Degrees_Degrees
        Areas:
          description: "Areas"
          display_name: "Areas"
          route: Core_HEd_Degrees_Areas

Core.HEd.Grading.Reports:
  parent: Core.HEd.Grading
  type: dir
  description: "Reports"
  display_name: "Reports"
  reports:
    StudentFinalGrades:
      description: "Final Grades"
      display_name: "Final Grades"
      route: Core_HEd_Grading_Reports_FinalGrades
    StudentTranscript:
      description: "Student Transcript"
      display_name: "Student Transcript"
      route: Core_HEd_Grading_Reports_StudentTranscript
    DegreeAudit:
      description: "Degree Audit"
      display_name: "Degree Audit"
      route: Core_HEd_Grading_Reports_DegreeAudit
    GradeRoster:
      description: "Grade Roster"
      display_name: "Grade Roster"
      route: Core_HEd_Grading_Reports_GradeRoster

Core.HEd.Scheduling.Section.Grades:
  type: tab
  parent: Core.HEd.Scheduling.Section
  description: "Grades"
  display_name: "Grades"
  route: Core_HEd_Scheduling_Section_Grades

Core.HEd.Scheduling.Section:
  menu_reports:
    GradeRoster:
      description: "Grade Roster"
      display_name: "Grade Roster"
      route: Core_HEd_Grading_Reports_GradeRoster

Core.HEd.Grading.GradingSetup:
  description: "Grading Setup"
  display_name: "Grading Setup"
  type: form
  parent: Core.HEd.Grading
  tabs:
    MarkScales:
      description: "Mark Scales"
      display_name: "Mark Scales"
      route: Core_HEd_Grading_GradingSetup_MarkScales
    Standings:
      description: "Standings"
      display_name: "Standings"
      route: Core_HEd_Grading_GradingSetup_Standings
    RepeatTags:
      description: "Repeat Tags"
      display_name: "Repeat Tags"
      route: Core_HEd_Grading_GradingSetup_RepeatTags

Teacher.HEd.Grades:
  parent: Teacher.HEd
  type: form
  description: "Grades"
  display_name: "Grades"
  tabs:
    Current:
      description: "Current"
      display_name: "Current"
      route: teacher_HEd_section_grades_current
    Dropped:
      description: "Dropped Roster"
      display_name: "Dropped"
      route: teacher_HEd_section_grades_dropped

Teacher.HEd.Advisee.DegreeAudit:
  parent: Teacher.HEd.Advisee
  type: tab
  description: "Degree Audit"
  display_name: "Degree Audit"
  route: teacher_HEd_student_degreeaudit

Teacher.HEd.Advisee.Transcript:
  parent: Teacher.HEd.Advisee
  type: tab
  description: "Transcript"
  display_name: "Transcript"
  route: teacher_HEd_student_transcript

Student.HEd.Grades:
  description: "Grades"
  display_name: "Grades"
  type: form
  parent: Student.HEd
  route: student_HEd_student_grades