_sis_HEd_coursehistory:
    resource: "@KulaHEdGradingBundle/Resources/config/routing/sis.yml"
    prefix: sis/HEd

_teacher_HEd_coursehistory:
    resource: "@KulaHEdGradingBundle/Resources/config/routing/teacher.yml"
    prefix: teacher/HEd

_student_HEd_coursehistory:
    resource: "@KulaHEdGradingBundle/Resources/config/routing/student.yml"
    prefix: student/HEd