_HEd_grading_api:
    resource: "@KulaHEdGradingBundle/Resources/config/routing/api.yml"
    prefix: api/v1

_sis_HEd_grading:
    resource: "@KulaHEdGradingBundle/Resources/config/routing/core.yml"
    prefix: core/HEd

_teacher_HEd_grading:
    resource: "@KulaHEdGradingBundle/Resources/config/routing/teacher.yml"
    prefix: teacher/HEd

_student_HEd_grading:
    resource: "@KulaHEdGradingBundle/Resources/config/routing/student.yml"
    prefix: student/HEd