imports:
    - { resource: schema/degree.yml }
    - { resource: schema/requirements.yml }
    - { resource: schema/grading.yml }
    - { resource: schema/coursehistory.yml }
    - { resource: schema/standing.yml }

HEd.Student.Status:
  fields:
    AcademicProbation:
      description: "Academic Probation"
      db_column_name: ACADEMIC_PROBATION
      db_column_type: bool
      db_column_null: false
      db_column_default: 0
      field_type: checkbox
      column_name: "Academic Probation"
      label_name: "Academic Probation"
HEd.Staff.OrganizationTerms:
  fields:
    TeacherGradesOpen:
      description: "Teacher Grades Open"
      db_column_name: TEACHER_GRADES_OPEN
      db_column_type: date
      db_column_null: true
      field_type: date
      column_name: "Teacher Grades Open"
      label_name: "Teacher Grades Open"
    TeacherGradesClose:
      description: "Teacher Grades Close"
      db_column_name: TEACHER_GRADES_CLOSE
      db_column_type: date
      db_column_null: true
      field_type: date
      column_name: "Teacher Grades Close"
      label_name: "Teacher Grades Close"
HEd.Section:
  fields:
    TeacherGradesCompleted:
      description: "Teacher Grades Completed"
      db_column_name: TEACHER_GRADES_COMPLETED
      db_column_type: bool
      db_column_default: 0
      db_column_null: false
      field_type: checkbox
      column_name: "Teacher Grades Completed"
      label_name: "Teacher Grades Completed"
    TeacherGradesCompletedUserstamp:
      description: "Teacher Grades Completed Userstamp"
      db_column_name: TEACHER_GRADES_COMPLETED_USERSTAMP
      db_column_type: serial
      db_column_null: true
      field_type: text
      field_size: 20
      column_name: "Teacher Grades Completed Userstamp"
      label_name: "Teacher Grades Completed Userstamp"
    TeacherGradesCompletedTimestamp:
      description: "Teacher Grades Completed Timestamp"
      db_column_name: TEACHER_GRADES_COMPLETED_TIMESTAMP
      db_column_type: datetime
      db_column_null: true
      field_type: datetime
      field_size: 20
      column_name: "Teacher Grades Completed Timestamp"
      label_name: "Teacher Grades Completed Timestamp"