services:
  kula.HEd.grading.coursehistory:
    class: Kula\HEd\Bundle\GradingBundle\Service\CourseHistoryService
    arguments: ["@kula.core.db", "@kula.core.poster_factory", "@kula.core.record"]

  kula.HEd.grading.termtotals:
    class: Kula\HEd\Bundle\GradingBundle\Service\TermTotalsService
    arguments: ["@kula.core.db", "@kula.core.poster_factory"]
    
  kula.HEd.grading.degreeaudit:
    class: Kula\HEd\Bundle\GradingBundle\Service\DegreeAuditService
    arguments: ["@kula.core.db"]

  kula.HEd.grading.transcript:
    class: Kula\HEd\Bundle\GradingBundle\Service\TranscriptService
    arguments: ["@kula.core.db"]