HEd.FAID.Code:
  description: "Award Codes"
  db_table_name: FAID_AWARD_CODE
  timestamps: true
  fields:
    ID:
      description: "ID"
      primary: true
      db_column_name: AWARD_CODE_ID
      db_column_type: primary_serial
      column_name: "Award Code ID"
      label_name: "Award Code ID"
    Code:
      description: "Code"
      db_column_name: AWARD_CODE
      db_column_type: varchar
      db_column_length: 25
      db_column_null: false
      field_type: text
      field_size: 10
      column_name: "Award Code"
      label_name: "Award Code"
    Description:
      description: "Description"
      db_column_name: AWARD_DESCRIPTION
      db_column_type: varchar
      db_column_length: 100
      db_column_null: false
      field_type: text
      field_size: 25
      column_name: "Award Description"
      label_name: "Award Description"
    Category:
      description: "Category"
      db_column_name: AWARD_CATEGORY
      db_column_type: varchar
      db_column_length: 5
      db_column_null: true
      field_type: lookup
      lookup: HEd.FAID.Code.Category
      column_name: "Award Category"
      label_name: "Award Category"
    Inactive:
      description: "Inactive"
      db_column_name: INACTIVE
      db_column_type: bool
      db_column_default: 0
      db_column_null: false
      field_type: checkbox
      column_name: "Inactive"
      label_name: "Inactive"
    ShowOnStatement:
      description: "Show on Statement"
      db_column_name: SHOW_ON_STATEMENT
      db_column_type: bool
      db_column_default: 0
      db_column_null: false
      field_type: checkbox
      column_name: "Show On Statement"
      label_name: "Show On Statement"
    TransactionCodeID:
      description: "Transaction Code ID"
      parent: Core.Billing.Code.ID
      db_column_name: TRANSACTION_CODE_ID
      db_column_type: serial
      db_column_null: true
      field_type: select
      class: Kula\Core\Bundle\BillingBundle\Field\TransactionCode
      column_name: "Transaction Code ID"
      label_name: "Transaction Code ID"
    OriginationFeePercentage:
      description: "Origination Fee Percentage"
      db_column_name: ORIGINATION_FEE_PERCENTAGE
      db_column_type: numeric
      db_column_length: 6
      db_column_precision: 3
      db_column_null: true
      field_type: text
      field_size: 8
      column_name: "Origination Fee Percentage"
      label_name: "Origination Fee Percentage"
    ConversionAwardCode:
      description: "Conversion Award Code"
      db_column_name: CONV_AWARD_CODE_NUMBER
      db_column_type: varchar
      db_column_length: 255
      db_column_null: true
      field_type: text
      field_size: 20
      column_name: "Conversion Award Code"
      label_name: "Conversion Award Code"

HEd.FAID.PFAID.POE:
  description: "PowerFAID POE Mapping"
  db_table_name: FAID_PFAID_POE
  timestamps: true
  fields:
    POEToken:
      description: "POE Token"
      primary: true
      db_column_name: poe_token
      db_column_type: int
      db_column_null: false
      column_name: "POE Token"
      label_name: "POE Token"
    TermID:
      description: "Term ID"
      parent: Core.Term.ID
      db_column_name: TERM_ID
      db_column_type: serial
      db_column_null: true
      field_type: chooser
      chooser: Core.Term
      column_name: "Term ID"
      label_name: "Term ID"
    Level:
      description: "Level"
      db_column_name: LEVEL
      db_column_type: varchar
      db_column_length: 5
      db_column_null: true
      field_type: lookup
      lookup: HEd.Student.Enrollment.Level
      column_name: "Level"
      label_name: "Level"
    CustomFieldTermCreditTotal:
      description: "Custom Field Term Credit Total"
      db_column_name: CUSTOM_TERM_CREDIT_TOTAL
      db_column_type: varchar
      db_column_length: 10
      db_column_null: true
      field_type: text
      field_size: 12
      column_name: "Custom Field Term Credit Total"
      label_name: "Custom Field Term Credit Total"