Core.Billing.Transaction:
  description: "Transactions"
  db_table_name: BILL_CONSTITUENT_TRANSACTIONS
  timestamps: true
  fields:
    ID:
      description: "ID"
      primary: true
      db_column_name: CONSTITUENT_TRANSACTION_ID
      db_column_type: primary_serial
      column_name: "Transaction ID"
      label_name: "Transaction ID"
    ConstituentID:
      description: "Constituent ID"
      parent: Core.Constituent.ID
      db_column_name: CONSTITUENT_ID
      db_column_type: serial
      field_type: chooser
      chooser: Core.Constituent
      column_name: "Constituent ID"
      label_name: "Constituent ID"
    OrganizationTermID:
      description: "Organization Term ID"
      parent: Core.Organization.Term.ID
      db_column_name: ORGANIZATION_TERM_ID
      db_column_type: serial
      db_column_null: true
      field_type: chooser
      chooser: Core.Organization.Term
      column_name: "Organization Term ID"
      label_name: "Organization Term ID"
    CodeID:
      description: "Transaction Code ID"
      parent: Core.Billing.Code.ID
      db_column_name: CODE_ID
      db_column_type: serial
      db_column_null: false
      field_type: select
      class: Kula\Core\Bundle\BillingBundle\Field\TransactionCode
      column_name: "Code ID"
      label_name: "Code"
    TransactionDate:
      description: "Transaction Date"
      db_column_name: TRANSACTION_DATE
      db_column_type: date
      db_column_null: false
      field_type: date
      column_name: "Transaction Date"
      label_name: "Transaction Date"
    Description:
      description: "Transaction Description"
      db_column_name: TRANSACTION_DESCRIPTION
      db_column_type: text
      db_column_null: true
      field_type: textarea
      column_name: "Transaction Description"
      label_name: "Transaction Description"
    Amount:
      description: "Amount"
      db_column_name: AMOUNT
      db_column_type: numeric
      db_column_length: 7
      db_column_precision: 2
      field_type: text
      field_size: 7
      column_name: "Amount"
      label_name: "Amount"
    OriginalAmount:
      description: "Original Amount"
      db_column_name: ORIGINAL_AMOUNT
      db_column_type: numeric
      db_column_length: 7
      db_column_precision: 2
      field_type: text
      field_size: 7
      column_name: "Original Amount"
      label_name: "Original Amount"
    AppliedBalance:
      description: "Applied Balance"
      db_column_name: APPLIED_BALANCE
      db_column_type: numeric
      db_column_length: 7
      db_column_precision: 2
      field_type: text
      field_size: 7
      column_name: "Applied Balance"
      label_name: "Applied Balance"
    Posted:
      description: "Posted"
      db_column_name: POSTED
      db_column_type: bool
      db_column_default: 0
      db_column_null: false
      field_type: checkbox
      column_name: "Posted"
      label_name: "Posted"
    ShowOnStatement: 
      description: "Show On Statement"
      db_column_name: SHOW_ON_STATEMENT
      db_column_type: bool
      db_column_default: 0
      db_column_null: false
      field_type: checkbox
      column_name: "Show On Statement"
      label_name: "Show On Statement"
    Voided: 
      description: "Voided"
      db_column_name: VOIDED
      db_column_type: bool
      db_column_default: 0
      db_column_null: false
      field_type: checkbox
      column_name: "Voided"
      label_name: "Voided"
    VoidedReason:
      description: "Voided Reason"
      db_column_name: VOIDED_REASON
      db_column_type: text
      db_column_null: true
      field_type: textarea
      column_name: "Voided Reason"
      label_name: "Voided Reason"
    VoidedUserstamp:
      description: "Voided Userstamp"
      parent: Core.User.ID
      db_column_name: VOIDED_USERSTAMP
      db_column_type: serial
      db_column_null: true
      field_type: text
      field_size: 20
      column_name: "Voided Userstamp"
      label_name: "Voided Userstamp"
    VoidedTimestamp:
      description: "Voided Timestamp"
      db_column_name: VOIDED_TIMESTAMP
      db_column_type: datetime
      db_column_null: true
      field_type: datetime
      column_name: "Voided Timestamp"
      label_name: "Voided Timestamp"
    ConversionTransactionNumber:
      description: "Conversion Transaction Number"
      db_column_name: CONV_TRANSACTION_NUMBER
      db_column_type: varchar
      db_column_length: 255
      db_column_null: true
      field_type: text
      field_size: 20
      column_name: "Conv Trans Num"
      label_name: "Conv Trans Num"
    RefundTransactionID:
      description: "Refund Transaction ID"
      db_column_name: REFUND_TRANSACTION_ID
      db_column_type: serial
      parent: HEd.Billing.Transaction.ID
      db_column_null: true
      column_name: "Refund Transaction ID"
      label_name: "Refund Transaction ID"
    PaymentID:
      description: "Payment ID"
      parent: Core.Billing.Payment.ID
      db_column_name: PAYMENT_ID
      db_column_type: serial
      db_column_null: true
      column_name: "Payment ID"
      label_name: "Payment ID"
    StudentClassID:
      description: "Student Class ID"
      parent: HEd.Student.Class.ID
      db_column_name: STUDENT_CLASS_ID
      db_column_type: serial
      db_column_null: true
      field_type: select
      class: Kula\HEd\Bundle\SchedulingBundle\Field\Classes
      column_name: "Student Class ID"
      label_name: "Student Class ID"