K12.School:
  description: "School"
  db_table_name: STUD_SCHOOL
  timestamps: true
  fields: 
    ID:
      description: "ID"
      primary: true
      parent: Core.Organization.ID
      db_column_name: SCHOOL_ID
      db_column_type: serial
      column_name: "School ID"
      label_name: "School ID"