core_HEd_school_schoolsetup_general:
  path: /setup/school/general
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreSchoolSetup:general
    _navigation: Core.HEd.Setup.School.General

core_HEd_school_schoolsetup_gradelevels:
  path: /setup/school/gradelevels
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreSchoolSetup:gradelevels
    _navigation: Core.HEd.Setup.School.GradeLevels

core_HEd_school_schoolsetup_levels:
  path: /setup/school/levels
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreSchoolSetup:levels
    _navigation: Core.HEd.Setup.School.Levels

core_HEd_school_schoolsetup_levels_fte:
  path: /setup/school/levels/{level_id}/fte
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreSchoolSetup:fte
    _navigation: Core.HEd.Setup.School.Levels
  
core_HEd_school_staff:
  path: /staff
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreStaff:index
    _navigation: Core.HEd.Staff.Staff.Information

core_HEd_school_staff_add:
  path: /staff/add
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreStaff:add
    _navigation: Core.HEd.Staff.Staff

core_HEd_school_staff_add_constituent:
  path: /staff/add/constituent
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreStaff:add_constituent
    _navigation: Core.HEd.Staff.Staff
  methods: [GET]

core_HEd_school_staff_chooser:
  path: /staff/chooser
  defaults: { _controller: KulaHEdSchoolBundle:CoreStaff:staff_chooser }
  methods: [GET]

core_HEd_school_staff_create_constituent:
  path: /staff/add/constituent
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreStaff:create_constituent
    _navigation: Core.HEd.Staff.Staff
  methods: [POST]

core_HEd_school_staff_delete:
  path: /staff/delete
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreStaff:delete
    _navigation: Core.HEd.Staff.Staff
  methods: [POST]

core_HEd_school_staff_orgterm_chooser:
  path: /staff/organizationterm/chooser
  defaults: { _controller: KulaHEdSchoolBundle:CoreStaff:staff_organizationterm_chooser }
  methods: [GET]

core_HEd_school_staff_orgterms:
  path: /staff/orgterms
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreStaff:staff_orgterms
    _navigation: Core.HEd.Staff.Staff.OrganizationTerms

core_HEd_school_staff_addresses:
  path: /staff/addresses
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreContactInfo:addresses
    _navigation: Core.HEd.Staff.Staff.Addresses

core_HEd_school_staff_addresses_detail:
  path: /staff/{id}/addresses/detail/{sub_id}
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreContactInfo:detail
    _navigation: Core.HEd.Staff.Staff.Addresses

core_HEd_school_staff_emailaddress:
  path: /staff/emailaddresses
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreContactInfo:emailAddresses
    _navigation: Core.HEd.Staff.Staff.EmailAddresses

core_HEd_school_staff_emergencycontacts:
  path: /staff/emergencycontacts
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreContactInfo:emergencyContacts
    _navigation: Core.HEd.Staff.Staff.EmergencyContacts

core_HEd_school_staff_phones:
  path: /staff/phones
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreContactInfo:phones
    _navigation: Core.HEd.Staff.Staff.Phones

core_HEd_school_staff_addresses_add:
  path: /staff/addresses/add
  defaults: 
    _controller: KulaHEdSchoolBundle:CoreContactInfo:add_address
    _navigation: Core.HEd.Staff.Staff.Addresses