HEd.Staff:
  description: "Staff"
  db_table_name: STUD_STAFF
  timestamps: true
  fields: 
    ID:
      description: "ID"
      primary: true
      db_column_name: STAFF_ID
      db_column_type: primary_serial
      column_name: "Staff ID"
      label_name: "Staff ID"
    ConversionStaffNumber:
      description: "Conversion Staff Number"
      db_column_name: CONV_STAFF_NUMBER
      db_column_type: varchar
      db_column_length: 255
      db_column_null: true
      field_type: text
      field_size: 25
      column_name: "Conversion Staff Number"
      label_name: "Conversion Staff Number"
    AbbreviatedName:
      description: "Abbreviated Name"
      db_column_name: ABBREVIATED_NAME
      db_column_type: varchar
      db_column_length: 30
      db_column_null: true
      field_type: text
      field_size: 25
      column_name: "Abbreviated Name"
      label_name: "Abbreviated Name"
    Department:
      description: "Department"
      db_column_name: DEPARTMENT
      db_column_type: varchar
      db_column_length: 5
      db_column_null: true
      field_type: lookup
      lookup: HEd.Course.Department
      column_name: "Department"
      label_name: "Department"
    Department2:
      description: "Department"
      db_column_name: DEPARTMENT_2
      db_column_type: varchar
      db_column_length: 5
      db_column_null: true
      field_type: lookup
      lookup: HEd.Course.Department
      column_name: "Department 2"
      label_name: "Department 2"
    Department3:
      description: "Department"
      db_column_name: DEPARTMENT_3
      db_column_type: varchar
      db_column_length: 5
      db_column_null: true
      field_type: lookup
      lookup: HEd.Course.Department
      column_name: "Department 3"
      label_name: "Department 3"
    Department4:
      description: "Department"
      db_column_name: DEPARTMENT_4
      db_column_type: varchar
      db_column_length: 5
      db_column_null: true
      field_type: lookup
      lookup: HEd.Course.Department
      column_name: "Department 4"
      label_name: "Department 4"
    DepartmentHead:
      description: "Department Head"
      db_column_name: DEPARTMENT_HEAD
      db_column_type: bool
      db_column_null: false
      db_column_default: 0
      field_type: checkbox
      column_name: "Department Head"
      label_name: "Department Head"
HEd.Staff.OrganizationTerm:
  description: "Staff in Terms"
  db_table_name: STUD_STAFF_ORGANIZATION_TERMS
  timestamps: true
  fields:
    ID:
      description: "ID"
      primary: true
      db_column_name: STAFF_ORGANIZATION_TERM_ID
      db_column_type: primary_serial
      column_name: "Staff Organization Term ID"
      label_name: "Staff Organization Term ID"
    StaffID:
      description: "Staff ID"
      parent: HEd.Staff.ID
      db_column_name: STAFF_ID
      db_column_type: serial
      db_column_null: false
      field_type: radio
      column_name: "Staff ID"
      label_name: "Staff ID"
    OrganizationTermID:
      description: "Organization Term ID"
      parent: Core.Organization.Term.ID
      db_column_name: ORGANIZATION_TERM_ID
      db_column_type: serial
      db_column_null: false
      field_type: chooser
      chooser: Core.Organization.Term
      column_name: "Organization Term ID"
      label_name: "Organization Term ID"
    ConversionStaffNumber:
      description: "Conversion Staff Number"
      db_column_name: CONV_STAFF_NUMBER
      db_column_type: varchar
      db_column_length: 255
      db_column_null: true
      field_type: text
      field_size: 25
      column_name: "Conversion Staff Number"
      label_name: "Conversion Staff Number"
    FTE:
      description: "FTE"
      db_column_name: FTE
      db_column_type: float
      db_column_length: 3
      db_column_precision: 2
      db_column_null: true
      field_type: text
      field_size: 5
      column_name: FTE
      label_name: FTE
    Department:
      description: "Department"
      db_column_name: DEPARTMENT
      db_column_type: varchar
      db_column_length: 5
      db_column_null: true
      field_type: lookup
      lookup: HEd.Staff.Department
      column_name: "Department"
      label_name: "Department"
  unique_keys:
    StaffOrganizationTerms: [ 'HEd.Staff.OrganizationTerm.StaffID', 'HEd.Staff.OrganizationTerm.OrganizationTermID' ]