HEd.School.Term:
  description: "School Term"
  db_table_name: STUD_SCHOOL_TERM
  timestamps: true
  fields: 
    ID:
      description: "ID"
      primary: true
      parent: Core.Organization.Term.ID
      db_column_name: SCHOOL_TERM_ID
      db_column_type: serial
      column_name: "School Term ID"
      label_name: "School Term ID"
    TeacherGradesOpen:
      description: "Open Date for Teacher Grades"
      db_column_name: TEACHER_GRADES_OPEN
      db_column_type: datetime
      db_column_null: true
      field_type: datetime
      column_name: "Teacher Open Grades"
      label_name: "Teacher Open Grades"
    TeacherGradesClose:
      description: "Close Date for Teacher Grades"
      db_column_name: TEACHER_GRADES_CLOSE
      db_column_type: datetime
      db_column_null: true
      field_type: datetime
      column_name: "Teacher Close Grades"
      label_name: "Teacher Close Grades"
HEd.School.Term.GradeLevel:
  description: "School Term Grade Level"
  db_table_name: STUD_SCHOOL_TERM_GRADE_LEVEL
  timestamps: true
  fields:
    ID:
      description: "ID"
      primary: true
      db_column_name: SCHOOL_TERM_GRADE_ID
      db_column_type: primary_serial
      column_name: "School Term Grade ID"
      label_name: "School Term Grade ID"
    OrganizationTermID:
      description: "Organization Term ID"
      db_column_name: ORGANIZATION_TERM_ID
      db_column_type: serial
      parent: Core.Organization.Term.ID
      column_name: "Organization Term ID"
      label_name: "Organization Term ID"
    Level:
      description: "Level"
      db_column_name: LEVEL
      db_column_type: varchar
      db_column_length: 5
      field_type: lookup
      lookup: HEd.Student.Enrollment.Level
      column_name: "Level"
      label_name: "Level"
    Grade:
      description: "Grade"
      db_column_name: GRADE
      db_column_type: varchar
      db_column_length: 5
      field_type: lookup
      lookup: HEd.Student.Enrollment.Grade
      column_name: "Grade"
      label_name: "Grade"
    NextGrade:
      description: "Next Grade"
      db_column_name: NEXT_GRADE
      db_column_type: varchar
      db_column_length: 5
      db_column_null: true
      field_type: lookup
      lookup: HEd.Student.Enrollment.Grade
      column_name: "Next Grade"
      label_name: "Next Grade"
    MaxHours:
      description: "Max Hours"
      db_column_name: MAX_HOURS
      db_column_type: numeric
      db_column_length: 7
      db_column_precision: 3
      db_column_default: 0.000
      field_type: text
      field_size: 8
      column_name: "Max Hours"
      label_name: "Max Hours"
HEd.School.Term.Level:
  description: "School Term Level"
  db_table_name: STUD_SCHOOL_TERM_LEVEL
  timestamps: true
  fields:
    ID:
      description: "ID"
      primary: true
      db_column_name: SCHOOL_TERM_LEVEL_ID
      db_column_type: primary_serial
      column_name: "School Term Level ID"
      label_name: "School Term Level ID"
    OrganizationTermID:
      description: "Organization Term ID"
      db_column_name: ORGANIZATION_TERM_ID
      db_column_type: serial
      parent: Core.Organization.Term.ID
      column_name: "Organization Term ID"
      label_name: "Organization Term ID"
    Level:
      description: "Level"
      db_column_name: LEVEL
      db_column_type: varchar
      db_column_length: 5
      field_type: lookup
      lookup: HEd.Student.Enrollment.Level
      column_name: "Level"
      label_name: "Level"
    MinimumFullTimeHours:
      description: "Minimum Full Time Hours"
      db_column_name: MIN_FULL_TIME_HOURS
      db_column_type: numeric
      db_column_length: 5
      db_column_precision: 3
      field_type: text
      field_size: 6
      column_name: "Minimum Full Time Hours"
      label_name: "Minimum Full Time Hours"
    MinimumPartTimeHours:
      description: "Minimum Part Time Hours"
      db_column_name: MIN_PART_TIME_HOURS
      db_column_type: numeric
      db_column_length: 5
      db_column_precision: 3
      field_type: text
      field_size: 6
      column_name: "Minimum Part Time Hours"
      label_name: "Minimum Part Time Hours"
    FTEFullTimeHours:
      description: "FTE Full Time Hours"
      db_column_name: FTE_FULL_TIME_HOURS
      db_column_type: numeric
      db_column_length: 5
      db_column_precision: 3
      field_type: text
      field_size: 6
      column_name: "FTE Full Time Hours"
      label_name: "FTE Full Time Hours"
HEd.School.Term.Level.FTE:
  description: "School Term Level"
  db_table_name: STUD_SCHOOL_TERM_LEVEL_FTE
  timestamps: true
  fields:
    ID:
      description: "ID"
      primary: true
      db_column_name: SCHOOL_TERM_LEVEL_FTE_ID
      db_column_type: primary_serial
      column_name: "School Term Level FTE ID"
      label_name: "School Term Level FTE ID"
    SchoolTermLevelID:
      description: "School Term Level ID"
      db_column_name: SCHOOL_TERM_LEVEL_ID
      db_column_type: serial
      parent: HEd.School.Term.Level.ID
      column_name: "School Term Level ID"
      label_name: "School Term Level ID"
    CreditTotal:
      description: "Credit Total"
      db_column_name: CREDIT_TOTAL
      db_column_type: numeric
      db_column_length: 6
      db_column_precision: 3
      field_type: text
      field_size: 5
      column_name: "Credit Total"
      label_name: "Credit Total"
    FTE:
      description: "FTE"
      db_column_name: FTE
      db_column_type: numeric
      db_column_length: 4
      db_column_precision: 3
      field_type: text
      field_size: 5
      column_name: "FTE"
      label_name: "FTE"