Core.Billing.Code.Type:
  description: "Billing Code Types"
  allow_update: false
  values:
    - { code: C, description: "Charge" }
    - { code: P, description: "Payment" }

Core.Billing.Payment.Type:
  description: "Billing Payment Types"
  allow_update: false
  values:
    - { code: D, description: "Discount" }
    - { code: P, description: "Payment" }
    - { code: R, description: "Refund" }

Core.Billing.Payment.Method:
  description: "Billing Payment Methods"
  allow_update: true
  values:
    - { code: CHK, description: "Check" }
    - { code: CREDIT, description: "Credit Card" }
    - { code: DEBIT, description: "Debit Card" }
    - { code: ACH, description: "ACH" }

Core.Billing.Fee.Discount:
  description: "Billing Discounts"
  allow_update: true