imports:
    - { resource: schema/code.yml }
    - { resource: schema/coursefee.yml }
    - { resource: schema/payments.yml }
    - { resource: schema/transactions.yml }
    - { resource: schema/tuitionrate.yml }