services:
  kula.Core.billing.transaction:
    class: Kula\Core\Bundle\BillingBundle\Service\TransactionService
    arguments: ["@kula.core.db", "@kula.core.poster_factory"]

  kula.Core.billing.payment:
    class: Kula\Core\Bundle\BillingBundle\Service\PaymentService
    arguments: ["@kula.core.db", "@kula.core.poster_factory"]

  kula.Core.billing.payment.merchant.VirtualMerchant:
    class: Kula\Core\Bundle\BillingBundle\Service\Merchant\VirtualMerchantService
    arguments: ["%virtualmerchant_url%", "%virtualmerchant_merchant_id%", "%virtualmerchant_user_id%", "%virtualmerchant_pin%"]