Core.Utility:
  description: "Utility"
  display_name: Utility
  type: form_group
  portal: core
  sort: 5
  forms:
    Export:
      description: "Export"
      display_name: "Export"
      route: core_export_query
      sort: 1

SIS.Utility:
  description: "Utility"
  display_name: Utility
  type: form_group
  portal: sis
  sort: 5
  forms:
    Export:
      description: "Export"
      display_name: "Export"
      route: core_export_savedqueries
      sort: 1