Core.Utility:
  description: "Utility"
  display_name: Utility
  type: dir
  portal: core
  forms:
    Export:
      description: "Export"
      display_name: "Export"
      route: Core_Export_SavedQueries