core_export_query:
  path: /core/export/query
  defaults: { _controller: KulaCoreQueryBundle:CoreExport:query }

core_export_savedqueries:
  path: /core/export/query/saved
  defaults: { _controller: KulaCoreQueryBundle:CoreExport:saved }

core_export_saved_detail:
  path: /core/export/saved/{id}
  defaults: { _controller: KulaCoreQueryBundle:CoreExport:saved_detail }
  methods: [GET]

core_export_reports_export_download:
  path: /core/export/query/download
  defaults: { _controller: KulaCoreQueryBundle:CoreExport:query_download }
  methods: [GET]

core_export_query_download_generate:
  path: /core/export/query/download
  defaults: { _controller: KulaCoreQueryBundle:CoreExport:query_download_export }
  methods: [POST]