Core.Constituent.Constituent:
  type: form
  parent: Core.Constituent
  description: "Constituent"
  display_name: "Constituent"
  route: Core_Constituent_Constituent

Core.Constituent.Combiner:
  type: form
  parent: Core.Constituent
  description: "Combiner"
  display_name: "Combiner"
  tabs:
    Constituent:
      description: "Constituent Combiner"
      display_name: "Constituent"
      route: Core_Constituent_Combiner