Core.Constituent:
  description: "Constituent"
  display_name: "Constituent"
  type: form_group
  portal: core
  sort: 1
  forms: 
    Constituent:
      description: "Constituent"
      display_name: "Constituent"
      route: sis_core_constituent_constituent
      sort: 1

SIS.Utility:
  description: "Utility"
  display_name: Utility
  type: form_group
  portal: sis
  sort: 5
  forms:
    Combiner:
      description: "Combiner"
      display_name: "Combiner"
      sort: 1
      tabs:
        Constituent:
          description: "Constituent Combiner"
          display_name: "Constituent"
          route: sis_core_constituent_combiner
          sort: 1