Core.Constituent.Constituent:
  description: "Constituent"
  display_name: "Constituent"
  type: form
  parent: Core.Constituent
  tabs: 
    Information:
      description: "Information"
      display_name: "Information"
      route: Core_Constituent_Constituent
    Addresses:
      description: "Addresses"
      display_name: "Addresses"
      route: Core_Constituent_addresses
    Phones:
      description: "Phones"
      display_name: "Phones"
      route: Core_Constituent_phones
    EmailAddresses:
      description: "Email Addresses"
      display_name: "Email Addresses"
      route: Core_Constituent_emailaddress
  menu_actions:
    NewAddress:
      description: "New Address"
      display_name: "New Address"
      record_loaded: true
      route: Core_Constituent_addresses_add
  button_add:
    route: Core_Constituent_add_constituent
  button_delete:
    route: Core_Constituent_delete_constituent

Core.Constituent.Combiner:
  type: form
  parent: Core.Constituent
  description: "Combiner"
  display_name: "Combiner"
  tabs:
    Constituent:
      description: "Constituent Combiner"
      display_name: "Constituent"
      route: Core_Constituent_Combiner

Core.Constituent.Searcher:
  type: form
  parent: Core.Constituent
  description: "Searcher"
  display_name: "Searcher"
  route: Core_Constituent_Constituent_Searcher