Core_Constituent_Constituent:
    path:     /core/constituent/constituent
    defaults: 
      _controller: KulaCoreConstituentBundle:Constituent:index
      _navigation: Core.Constituent.Constituent.Information
    
Core_Constituent_Chooser:
    path: /core/constituent/chooser
    defaults: { _controller: KulaCoreConstituentBundle:Constituent:chooser }

Core_Constituent_Combiner:
    path:     /core/constituent/combiner
    defaults: 
      _controller: KulaCoreConstituentBundle:Constituent:combine
      _navigation: Core.Constituent.Combiner.Constituent

Core_Constituent_addresses:
  path: /core/constituent/addresses
  defaults: 
    _controller: KulaCoreConstituentBundle:CoreContactInfo:addresses
    _navigation: Core.Constituent.Constituent.Addresses

Core_Constituent_addresses_detail:
  path: /core/constituent/addresses/detail/{sub_id}
  defaults: 
    _controller: KulaCoreConstituentBundle:CoreContactInfo:detail
    _navigation: Core.Constituent.Constituent.Addresses

Core_Constituent_emailaddress:
  path: /core/constituent/emailaddresses
  defaults: 
    _controller: KulaCoreConstituentBundle:CoreContactInfo:emailAddresses
    _navigation: Core.Constituent.Constituent.EmailAddresses

Core_Constituent_phones:
  path: /core/constituent/phones
  defaults: 
    _controller: KulaCoreConstituentBundle:CoreContactInfo:phones
    _navigation: Core.Constituent.Constituent.Phones

Core_Constituent_addresses_add:
  path: /core/constituent/addresses/add
  defaults: 
    _controller: KulaCoreConstituentBundle:CoreContactInfo:add_address
    _navigation: Core.Constituent.Constituent.Addresses

Core_Constituent_add_constituent:
  path: /core/constituent/add/constituent
  defaults: 
    _controller: KulaCoreConstituentBundle:Constituent:add_constituent
    _navigation: Core.Constituent.Constituent
  methods: [GET]

Core_Constituent_create_constituent:
  path: /core/constituent/add/constituent
  defaults: 
    _controller: KulaCoreConstituentBundle:Constituent:create_constituent
    _navigation: Core.Constituent.Constituent
  methods: [POST]

Core_Constituent_delete_constituent:
  path: /staff/delete
  defaults: 
    _controller: KulaCoreConstituentBundle:Constituent:delete
    _navigation: Core.Constituent.Constituent
  methods: [POST]

Core_Constituent_Constituent_Searcher:
    path:     /core/constituent/search
    defaults: 
      _controller: KulaCoreConstituentBundle:CoreConstituentSearch:index
      _navigation: Core.Constituent.Searcher

Core_Constituent_relationships:
  path: /core/constituent/relationships
  defaults: 
    _controller: KulaCoreConstituentBundle:Constituent:relationships
    _navigation: Core.Constituent.Constituent.Relationships