Core_Constituent_Constituent:
    path:     /core/constituent/constituent
    defaults: 
      _controller: KulaCoreConstituentBundle:Constituent:index
      _navigation: Core.Constituent.Constituent
    
Core_Constituent_Chooser:
    path: /core/constituent/chooser
    defaults: { _controller: KulaCoreConstituentBundle:Constituent:chooser }

Core_Constituent_Combiner:
    path:     /core/constituent/combiner
    defaults: 
      _controller: KulaCoreConstituentBundle:Constituent:combine
      _navigation: Core.Constituent.Combiner.Constituent