services:
  kula.Core.Combine:
    class: Kula\Core\Bundle\ConstituentBundle\Service\CombineService
    arguments: ["@kula.core.db"]

  kula.Core.Constituent:
    class: Kula\Core\Bundle\ConstituentBundle\Service\ConstituentService
    arguments: ["@kula.core.db", "@kula.core.sequence", "@kula.core.poster_factory"]

  kula.Core.ContactInfo:
    class: Kula\Core\Bundle\ConstituentBundle\Service\ContactInfoService
    arguments: ["@kula.core.db", "@kula.core.poster_factory"]

  kula.Core.Constituent.Document:
    class: Kula\Core\Bundle\ConstituentBundle\Service\ConstituentDocumentService
    arguments: ["@kula.core.db", "@kula.core.session", "@kula.core.poster_factory"]
