services:
  kula.core.db:
    class:        Kula\Core\Component\DB\DB
    arguments:    [ %kernel.root_dir% , %kernel.environment% ]
  kula.core.poster:
    class: Kula\Core\Component\DB\Poster
    arguments: ["@kula.core.db", "@request_stack", "@kula.core.schema"]
    scope: prototype
  kula.core.data_collector.database:
    class: Kula\Core\Component\DB\DataCollector\DatabaseDataCollector
    arguments: ["@kula.core.db"]
    priority: 255
    tags:
      - { name: data_collector, template: "KulaCoreFrameworkBundle:Collector:database.html.twig", id: "database" }
  kula.core.listener.authenticated_user:
    class: Kula\Core\Bundle\FrameworkBundle\EventListener\AuthenticatedUserListener
    arguments: ["@router", "@service_container"]
    tags:
      - { name: kernel.event_subscriber }