parameters:
  kula.core.poster_factory.class: Kula\Core\Component\DB\PosterFactory

services:
  flash:
    class: Symfony\Component\HttpFoundation\Session\Flash\FlashBag
    factory: ["@session", "getFlashBag"]
   
  kula.routing_loader:
    class: Kula\Core\Bundle\FrameworkBundle\Routing\BundleLoader
    arguments: ["@kernel"]
    tags:
      - { name: routing.loader }
   
  kula.core.exception:
    class: Kula\Core\Bundle\FrameworkBundle\EventListener\ExceptionListener
    tags: 
      - { name: kernel.event_subscriber }
      - { name: monolog.logger, channel: request }
  
  kula.core.controller:
    class: Kula\Core\Bundle\FrameworkBundle\EventListener\ControllerListener
    arguments: ["@request_stack", "@kula.core.focus", "@kula.core.session"]
    tags:
      - { name: kernel.event_subscriber }
  
  kula.core.db:
    class:        Kula\Core\Component\DB\DB
    arguments:    [ %kernel.root_dir% , %kernel.environment% ]
  kula.core.data_collector.database:
    class: Kula\Core\Component\DB\DataCollector\DatabaseDataCollector
    arguments: ["@kula.core.db"]
    priority: 255
    tags:
      - { name: data_collector, template: "KulaCoreFrameworkBundle:Collector:database.html.twig", id: "database" }
  kula.core.listener.authenticated_user:
    class: Kula\Core\Bundle\FrameworkBundle\EventListener\AuthenticatedUserListener
    arguments: ["@router", "@service_container"]
    tags:
      - { name: kernel.event_subscriber }

  kula.core.poster_factory:
    class: Kula\Core\Component\DB\PosterFactory
    factory: ["%kula.core.poster_factory.class%", "getPoster"]
    arguments: ["@service_container"]
    container: prototype
  
  kula.core.poster:
    class: Kula\Core\Component\DB\Poster
    factory: ["%kula.core.poster_factory.class%", "getPoster"]
    arguments: ["@service_container"]
  
  kula.core.searcher:
    class: Kula\Core\Component\DB\Searcher
    arguments: ["@kula.core.db", "@kula.core.schema", "@kula.core.permission", "@request_stack"]
  
  kula.core.session:
    class: Kula\Core\Bundle\FrameworkBundle\Service\Session
    arguments: ["@session", "@kula.core.db", "@request_stack"]
    
  kula.core.twig.extension:
    class: Kula\Core\Bundle\FrameworkBundle\Extension\TwigExtension
    arguments: ["@service_container"]
    public: false
    tags:
      - { name: twig.extension }
  
  kula.core.permission:
    class: Kula\Core\Component\Permission\Permission
    arguments: ["@kula.core.db", "@kula.core.session"]
    
  kula.core.focus:
    class:        Kula\Core\Bundle\FrameworkBundle\Service\Focus
    arguments:    ["@kula.core.session", "@kula.core.db", "@kula.core.poster", "@kula.core.organization", "@kula.core.term"] 
    
  kula.core.record:
    class: Kula\Core\Bundle\FrameworkBundle\Service\Record
    arguments: ["@kula.core.db", "@kula.core.session", "@kula.core.schema", "@kula.core.focus", "@request_stack", "@flash", "@kula.core.permission", "@kula.core.record_type"]