parameters:
  kula.core.poster_factory.class: Kula\Core\Component\DB\PosterFactory

services:
  flash:
    class: Symfony\Component\HttpFoundation\Session\Flash\FlashBag
    factory: ["@session", "getFlashBag"]
   
  kula.listener.requestmobile:
      class: Kula\Core\Bundle\FrameworkBundle\KulaCoreFrameworkBundle
      tags:
        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
   
  kula.routing_loader:
    class: Kula\Core\Bundle\FrameworkBundle\Routing\BundleLoader
    arguments: ["@kernel"]
    tags:
      - { name: routing.loader }
   
  kula.core.exception:
    class: Kula\Core\Bundle\FrameworkBundle\EventListener\ExceptionListener
    arguments: ['@service_container']
    tags: 
      - { name: kernel.event_subscriber }
      - { name: monolog.logger, channel: request }
  
  kula.core.controller:
    class: Kula\Core\Bundle\FrameworkBundle\EventListener\ControllerListener
    arguments: ["@request_stack", "@kula.core.focus", "@kula.core.session"]
    tags:
      - { name: kernel.event_subscriber }

  kula.core.api:
    class: Kula\Core\Bundle\FrameworkBundle\EventListener\APIListener
    arguments: ["@kula.core.db", "@kula.core.session", "@kula.core.api_logger"]
    tags:
      - { name: kernel.event_subscriber }
  
  kula.core.db:
    class:        Kula\Core\Component\DB\DB
    arguments:    [ '%kernel.root_dir%' , '%kernel.environment%' ]

  kula.core.data_collector.database:
    class: Kula\Core\Component\DB\DataCollector\DatabaseDataCollector
    arguments: ["@kula.core.db"]
    tags:
      - { name: data_collector, template: "KulaCoreFrameworkBundle:Collector:database.html.twig", id: "database" }

  kula.core.listener.authenticated_user:
    class: Kula\Core\Bundle\FrameworkBundle\EventListener\AuthenticatedUserListener
    arguments: ["@router", "@service_container"]
    tags:
      - { name: kernel.event_subscriber }

  kula.core.api_logger:
    class: Kula\Core\Bundle\FrameworkBundle\Service\APILogger
    arguments: ["@kula.core.db", "@session"]

  kula.core.poster_factory:
    class: Kula\Core\Component\DB\PosterFactory
    arguments: ["@service_container"]
  
  kula.core.poster:
    class: Kula\Core\Component\DB\Poster
    factory: ["%kula.core.poster_factory.class%", "getPoster"]
    arguments: ["@service_container"]
  
  kula.core.searcher:
    class: Kula\Core\Component\DB\Searcher
    arguments: ["@kula.core.db", "@kula.core.schema", "@kula.core.permission", "@request_stack"]

  kula.core.sequence:
    class: Kula\Core\Bundle\FrameworkBundle\Service\Sequence
    arguments: ["@kula.core.db"]
  
  kula.core.session:
    class: Kula\Core\Bundle\FrameworkBundle\Service\Session
    arguments: ["@session", "@kula.core.db", "@request_stack", "@kula.core.organization"]
    
  kula.core.twig.extension:
    class: Kula\Core\Bundle\FrameworkBundle\Extension\TwigExtension
    arguments: ["@service_container"]
    public: false
    tags:
      - { name: twig.extension }
  
  kula.core.permission:
    class: Kula\Core\Component\Permission\Permission
    arguments: ["@kula.core.db", "@kula.core.session"]
    
  kula.core.focus:
    class:        Kula\Core\Bundle\FrameworkBundle\Service\Focus
    arguments:    ["@kula.core.session", "@kula.core.db", "@kula.core.poster", "@kula.core.organization", "@kula.core.term"] 
    
  kula.core.record:
    class: Kula\Core\Bundle\FrameworkBundle\Service\Record
    arguments: ["@kula.core.db", "@kula.core.session", "@kula.core.schema", "@kula.core.focus", "@request_stack", "@flash", "@kula.core.permission", "@kula.core.record_type", "@kula.core.searcher"]

  kula.core.cache.apc:
    class: Kula\Core\Component\Cache\APCCache
    arguments: ["@service_container"]
  
  kula.core.cache.kv:
    class: Kula\Core\Component\Cache\KVCache
    arguments: ["@service_container", "@kula.core.cache.apc"]
