Core_System_Lookup:
  path: /system/lookup
  defaults: 
    _controller: KulaCoreSystemBundle:CoreLookup:index
    _navigation: Core.System.Lookup

Core_System_Lookup_Add:
  path: /system/lookup/new
  defaults: 
    _controller: KulaCoreSystemBundle:CoreLookup:add
    _navigation: Core.System.Lookup.button_add
  methods: [GET]

Core_System_Lookup_Chooser:
  path: /system/lookup/chooser
  defaults: { _controller: KulaCoreSystemBundle:CoreLookup:chooser }
  methods: [GET]

Core_System_Lookup_Create:
  path: /system/lookup/new
  defaults: 
    _controller: KulaCoreSystemBundle:CoreLookup:create
    _navigation: Core.System.Lookup.button_add
  methods: [POST]

Core_System_Lookup_Delete:
  path: /system/lookup/delete
  defaults: 
    _controller: KulaCoreSystemBundle:CoreLookup:delete
    _navigation: Core.System.Lookup.button_delete
  methods: [POST]

Core_System_NavPermissions_Public:
  path: /system/permissions/navigation/public
  defaults: 
    _controller: KulaCoreSystemBundle:CoreNavigationPermissions:public_permissions
    _navigation: Core.System.NavigationPermissions.Public

Core_System_NavPermissions_Role:
  path: /system/permissions/navigation/role
  defaults: 
    _controller: KulaCoreSystemBundle:CoreNavigationPermissions:role
    _navigation: Core.System.NavigationPermissions.Role

Core_System_NavPermissions_Usergroup:
  path: /system/permissions/navigation/usergroup
  defaults: 
    _controller: KulaCoreSystemBundle:CoreNavigationPermissions:usergroup
    _navigation: Core.System.NavigationPermissions.UserGroup

Core_System_NonOrganization:
  path: /system/nonorganization
  defaults: 
    _controller: KulaCoreSystemBundle:CoreNonOrganization:index
    _navigation: Core.System.NonOrganization

Core_System_NonOrganization_Add:
  path: /system/nonorganization/new
  defaults: 
    _controller: KulaCoreSystemBundle:CoreNonOrganization:add
    _navigation: Core.System.NonOrganization.New
  methods: [GET]

Core_System_NonOrganization_Create:
  path: /system/nonorganization/new
  defaults: 
    _controller: KulaCoreSystemBundle:CoreNonOrganization:create
    _navigation: Core.System.NonOrganization.New
  methods: [POST]
  
Core_System_NonOrganization_Delete:
  path: /system/nonorganization/delete
  defaults: 
    _controller: KulaCoreSystemBundle:CoreNonOrganization:delete
    _navigation: Core.System.NonOrganization.Delete
  methods: [POST]

Core_System_NonOrganization_Chooser:
  path: /system/nonorganization/chooser
  defaults: { _controller: KulaCoreSystemBundle:CoreNonOrganization:chooser }

Core_System_Organization:
  path: /system/organization
  defaults: 
    _controller: KulaCoreSystemBundle:CoreOrganization:index
    _navigation: Core.System.Organization.Organization

Core_System_Organization_Chooser:
  path: /system/organization/chooser
  defaults: { _controller: KulaCoreSystemBundle:CoreOrganization:chooser }
  methods: [GET]

Core_System_Organization_OrgTerm_Chooser:
  path: /system/organization/terms/chooser
  defaults: { _controller: KulaCoreSystemBundle:CoreOrganization:org_term_chooser }
  methods: [GET]

Core_System_Organization_Terms:
  path: /system/organization/terms
  defaults: 
    _controller: KulaCoreSystemBundle:CoreOrganization:orgterms_index
    _navigation: Core.System.Organization.OrganizationTerms

Core_System_Organization_Terms_Edit:
  path: /system/organization/{id}/terms
  defaults: 
    _controller: KulaCoreSystemBundle:CoreOrganization:orgterms_index
    _navigation: Core.System.Organization.OrganizationTerms

Core_System_SchemaPermissions_Field_Public:
  path: /system/permissions/schema/public/table/{schema_table_id}
  defaults: 
    _controller: KulaCoreSystemBundle:CoreSchemaFieldPermissions:public_permissions
    _navigation: Core.System.SchemaPermissions.Public

Core_System_SchemaPermissions_Field_Role:
  path: /system/permissions/schema/role/table/{schema_table_id}
  defaults: 
    _controller: KulaCoreSystemBundle:CoreSchemaFieldPermissions:role
    _navigation: Core.System.SchemaPermissions.Role

Core_System_SchemaPermissions_Field_Usergroup:
  path: /system/permissions/schema/usergroup/table/{schema_table_id}
  defaults: 
    _controller: KulaCoreSystemBundle:CoreSchemaFieldPermissions:usergroup
    _navigation: Core.System.SchemaPermissions.UserGroup

Core_System_SchemaPermissions_Public:
  path: /system/permissions/schema/public
  defaults: 
    _controller: KulaCoreSystemBundle:CoreSchemaPermissions:public_permissions
    _navigation: Core.System.SchemaPermissions.Public

Core_System_SchemaPermissions_Role:
  path: /system/permissions/schema/role
  defaults: 
    _controller: KulaCoreSystemBundle:CoreSchemaPermissions:role
    _navigation: Core.System.SchemaPermissions.Role

Core_System_SchemaPermissions_Usergroup:
  path: /system/permissions/schema/usergroup
  defaults: 
    _controller: KulaCoreSystemBundle:CoreSchemaPermissions:usergroup
    _navigation: Core.System.SchemaPermissions.UserGroup

Core_System_Terms:
  path: /system/terms
  defaults: 
    _controller: KulaCoreSystemBundle:CoreTerms:index
    _navigation: Core.System.Terms

Core_System_Terms_Chooser:
  path: /system/terms/chooser
  defaults: { _controller: KulaCoreSystemBundle:CoreTerms:chooser }
  methods: [GET]

Core_System_Usergroups:
  path: /system/usergroups
  defaults: 
    _controller: KulaCoreSystemBundle:CoreUserGroups:index
    _navigation: Core.System.UserGroups

Core_System_Usergroups_Chooser:
  path: /system/usergroups/chooser
  defaults: { _controller: KulaCoreSystemBundle:CoreUserGroups:chooser }
  methods: [GET]

Core_System_Users:
  path: /system/users
  defaults: 
    _controller: KulaCoreSystemBundle:CoreUsers:index
    _navigation: Core.System.Users.Information

Core_System_Users_Add:
  path: /system/users/add
  defaults: 
    _controller: KulaCoreSystemBundle:CoreUsers:add
    _navigation: Core.System.Users.Add

Core_System_Users_ResetLoginAttempts:
  path: /system/users/add/resetLoginAttempts
  defaults:
    _controller: KulaCoreSystemBundle:CoreUsers:resetFailedLoginAttempts
    _navigation: Core.System.Users.Information

Core_System_Users_Add_Constituent:
  path: /system/users/add/constituent
  defaults:
    _controller: KulaCoreSystemBundle:CoreUsers:add_constituent
    _navigation: Core.System.Users.Add
  methods: [GET]

Core_System_Users_Create_Constituent:
  path: /system/users/add/constituent
  defaults: 
    _controller: KulaCoreSystemBundle:CoreUsers:create_constituent
    _navigation: Core.System.Users.Add
  methods: [POST]

Core_System_Users_Delete:
  path: /system/users/delete
  defaults: 
    _controller: KulaCoreSystemBundle:CoreUsers:delete
    _navigation: Core.System.Users.Delete
  methods: [POST]

Core_System_Users_Edit_Usergroups:
  path: /system/users/{id}/usergroups
  defaults: 
    _controller: KulaCoreSystemBundle:CoreUsers:user_groups
    _navigation: Core.System.Users.UserGroups

Core_System_Users_Usergroups:
  path: /system/users/usergroups
  defaults: 
    _controller: KulaCoreSystemBundle:CoreUsers:user_groups
    _navigation: Core.System.Users.UserGroups

Core_Setup_System:
  path: /setup/system
  defaults: 
    _controller: KulaCoreSystemBundle:CoreSetup:index
    _navigation: Core.System.Setup.General

Core_Setup_System_LDAP:
  path: /setup/system/ldap
  defaults: 
    _controller: KulaCoreSystemBundle:CoreSetup:ldap
    _navigation: Core.System.Setup.LDAP

Core_Logs_Session:
  path: /monitor/logs/session
  defaults: 
    _controller: KulaCoreSystemBundle:CoreLogs:session
    _navigation: Core.System.Monitor.Logs

Core_Logs_API_Session:
  path: /monitor/logs/api/session
  defaults: 
    _controller: KulaCoreSystemBundle:CoreAPILogs:session
    _navigation: Core.System.Monitor.APILogs.Sessions

Core_Logs_API_Session_Requests:
  path: /monitor/logs/api/session/{session_id}/requests
  defaults: 
    _controller: KulaCoreSystemBundle:CoreAPILogs:requestsForSession

Core_Logs_API_Session_Requests_Error:
  path: /monitor/logs/api/requests/error
  defaults: 
    _controller: KulaCoreSystemBundle:CoreAPILogs:errorRequests
    _navigation: Core.System.Monitor.APILogs.ErrorRequests

Core_Logs_API_Session_User:
  path: /monitor/logs/api/session/user
  defaults: 
    _controller: KulaCoreSystemBundle:CoreAPILogs:sessionsForUser
    _navigation: Core.System.Monitor.APILogs.User

Core_Logs_API_Session_User_Requests:
  path: /monitor/logs/api/session/{session_id}/user/requests
  defaults: 
    _controller: KulaCoreSystemBundle:CoreAPILogs:requestsForSession

Core_System_Integration_Databases:
  path: /setup/system/integration/databases
  defaults: 
    _controller: KulaCoreSystemBundle:CoreIntegration:databases
    _navigation: Core.System.Setup.IntegrationDatabases

Core_System_Integration_API_Apps:
  path: /setup/system/integration/api_apps
  defaults: 
    _controller: KulaCoreSystemBundle:CoreIntegration:apiApps
    _navigation: Core.System.Setup.IntegrationAPIApps