Core.Chooser:
  description: "Choosers"
  db_table_name: CORE_CHOOSER
  timestamps: true
  fields:
    ID:
      description: "Chooser ID"
      primary: true
      db_column_name: CHOOSER_ID
      db_column_type: primary_serial
      field_type: text
      field_size: 5
      column_name: "Chooser ID"
      label_name: "Chooser ID"
    ChooserName:
      description: "Chooser Name"
      db_column_name: CHOOSER_NAME
      db_column_type: varchar
      db_column_length: 255
      db_column_null: false
      field_type: text
      field_size: 20
      column_name: "Chooser Name"
      label_name: "Chooser Name"
    Class:
      description: "Class File"
      db_column_name: CLASS
      db_column_type: text
      db_column_null: false
      field_type: text
      field_size: 40
      column_name: "Class File"
      label_name: "Class File"