Core.Navigation:
  description: "Navigation Table"
  db_table_name: CORE_NAVIGATION
  timestamps: true
  fields:
    ID:
      description: "ID"
      primary: true
      db_column_name: NAVIGATION_ID
      db_column_type: primary_serial
      field_type: text
      field_size: 5
      column_name: "Navigation ID"
      label_name: "Navigation ID"
    Parent:
      description: "Parent ID"
      parent: Core.Navigation.ID
      db_column_name: PARENT_NAVIGATION_ID
      db_column_type: serial
      db_column_null: true
      field_type: text
      field_size: 5
      column_name: "Parent Navigation ID"
      label_name: "Parent Navigation ID"
    Name:
      description: "Name"
      db_column_name: NAVIGATION_NAME
      db_column_type: varchar
      db_column_length: 255
      db_column_null: false
      field_type: text
      field_size: 30
      column_name: "Navigation Name"
      label_name: "Navigation Name"
    Type:
      description: "Type"
      db_column_name: NAVIGATION_TYPE
      db_column_type: varchar
      db_column_length: 20
      db_column_null: false
      field_type: lookup
      lookup: Core.Navigation.Type
      column_name: "Type"
      label_name: "Type"
    Portal:
      description: "Portal"
      db_column_name: PORTAL
      db_column_type: varchar
      db_column_length: 10
      db_column_null: false
      field_type: lookup
      lookup: Core.Navigation.Portal
      column_name: "Portal"
      label_name: "Portal"
    Sort:
      description: "Sort"
      db_column_name: SORT
      db_column_type: int
      db_column_size: tiny
      db_column_null: true
      field_type: text
      field_size: 5
      column_name: "Sort"
      label_name: "Sort"
    DisplayName:
      description: "Display Name"
      db_column_name: DISPLAY_NAME
      db_column_type: varchar
      db_column_length: 50
      db_column_null: false
      field_type: text
      field_size: 50
      column_name: "Display Name"
      label_name: "Display Name"
    DividerBefore:
      description: "Divider Before"
      db_column_name: DIVIDER_BEFORE
      db_column_type: bool
      db_column_default: 0
      db_column_null: false
      field_type: checkbox
      column_name: "Divider Before"
      label_name: "Divider Before"
    RecordLoaded:
      description: "Record Loaded"
      db_column_name: RECORD_LOADED
      db_column_type: bool
      db_column_default: 0
      db_column_null: false
      field_type: checkbox
      column_name: "Record Loaded"
      label_name: "Record Loaded"
    Route:
      description: "Route"
      db_column_name: ROUTE
      db_column_type: varchar
      db_column_length: 255
      db_column_null: true
      field_type: text
      field_size: 25
      column_name: "Route"
      label_name: "Route"
    Confirmation:
      description: "Confirmation Prompt Message"
      db_column_name: CONFIRMATION_MESSAGE
      db_column_type: text
      db_column_null: true
      field_type: textarea
      field_rows: 15
      field_cols: 40
      column_name: "Confirmation"
      label_name: "Confirmation"